// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/v1/datasource.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataSource_CreateDataSource_FullMethodName          = "/sovereign.api.v1.DataSource/CreateDataSource"
	DataSource_UpdateDataSource_FullMethodName          = "/sovereign.api.v1.DataSource/UpdateDataSource"
	DataSource_UpdateDataSourceStatus_FullMethodName    = "/sovereign.api.v1.DataSource/UpdateDataSourceStatus"
	DataSource_DeleteDataSource_FullMethodName          = "/sovereign.api.v1.DataSource/DeleteDataSource"
	DataSource_GetDataSource_FullMethodName             = "/sovereign.api.v1.DataSource/GetDataSource"
	DataSource_ListDataSource_FullMethodName            = "/sovereign.api.v1.DataSource/ListDataSource"
	DataSource_SelectDataSource_FullMethodName          = "/sovereign.api.v1.DataSource/SelectDataSource"
	DataSource_TestConnection_FullMethodName            = "/sovereign.api.v1.DataSource/TestConnection"
	DataSource_QueryDataSource_FullMethodName           = "/sovereign.api.v1.DataSource/QueryDataSource"
	DataSource_ListQueryHistory_FullMethodName          = "/sovereign.api.v1.DataSource/ListQueryHistory"
	DataSource_SaveQueryFavorite_FullMethodName         = "/sovereign.api.v1.DataSource/SaveQueryFavorite"
	DataSource_ListQueryFavorites_FullMethodName        = "/sovereign.api.v1.DataSource/ListQueryFavorites"
	DataSource_DeleteQueryFavorite_FullMethodName       = "/sovereign.api.v1.DataSource/DeleteQueryFavorite"
	DataSource_CreateAlertTemplate_FullMethodName       = "/sovereign.api.v1.DataSource/CreateAlertTemplate"
	DataSource_UpdateAlertTemplate_FullMethodName       = "/sovereign.api.v1.DataSource/UpdateAlertTemplate"
	DataSource_DeleteAlertTemplate_FullMethodName       = "/sovereign.api.v1.DataSource/DeleteAlertTemplate"
	DataSource_GetAlertTemplate_FullMethodName          = "/sovereign.api.v1.DataSource/GetAlertTemplate"
	DataSource_ListAlertTemplate_FullMethodName         = "/sovereign.api.v1.DataSource/ListAlertTemplate"
	DataSource_UpdateAlertTemplateStatus_FullMethodName = "/sovereign.api.v1.DataSource/UpdateAlertTemplateStatus"
	DataSource_ApplyAlertTemplate_FullMethodName        = "/sovereign.api.v1.DataSource/ApplyAlertTemplate"
	DataSource_CreateDataSourceProxy_FullMethodName     = "/sovereign.api.v1.DataSource/CreateDataSourceProxy"
	DataSource_UpdateDataSourceProxy_FullMethodName     = "/sovereign.api.v1.DataSource/UpdateDataSourceProxy"
	DataSource_DeleteDataSourceProxy_FullMethodName     = "/sovereign.api.v1.DataSource/DeleteDataSourceProxy"
	DataSource_GetDataSourceProxy_FullMethodName        = "/sovereign.api.v1.DataSource/GetDataSourceProxy"
	DataSource_ListDataSourceProxy_FullMethodName       = "/sovereign.api.v1.DataSource/ListDataSourceProxy"
	DataSource_ListDataSourceMetadata_FullMethodName    = "/sovereign.api.v1.DataSource/ListDataSourceMetadata"
	DataSource_GetDataSourceMetadata_FullMethodName     = "/sovereign.api.v1.DataSource/GetDataSourceMetadata"
	DataSource_RefreshDataSourceMetadata_FullMethodName = "/sovereign.api.v1.DataSource/RefreshDataSourceMetadata"
)

// DataSourceClient is the client API for DataSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataSourceClient interface {
	CreateDataSource(ctx context.Context, in *CreateDataSourceRequest, opts ...grpc.CallOption) (*CreateDataSourceReply, error)
	UpdateDataSource(ctx context.Context, in *UpdateDataSourceRequest, opts ...grpc.CallOption) (*UpdateDataSourceReply, error)
	UpdateDataSourceStatus(ctx context.Context, in *UpdateDataSourceStatusRequest, opts ...grpc.CallOption) (*UpdateDataSourceStatusReply, error)
	DeleteDataSource(ctx context.Context, in *DeleteDataSourceRequest, opts ...grpc.CallOption) (*DeleteDataSourceReply, error)
	GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSourceItem, error)
	ListDataSource(ctx context.Context, in *ListDataSourceRequest, opts ...grpc.CallOption) (*ListDataSourceReply, error)
	SelectDataSource(ctx context.Context, in *SelectDataSourceRequest, opts ...grpc.CallOption) (*SelectDataSourceReply, error)
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionReply, error)
	// 及时查询相关接口
	QueryDataSource(ctx context.Context, in *QueryDataSourceRequest, opts ...grpc.CallOption) (*QueryDataSourceReply, error)
	ListQueryHistory(ctx context.Context, in *ListQueryHistoryRequest, opts ...grpc.CallOption) (*ListQueryHistoryReply, error)
	SaveQueryFavorite(ctx context.Context, in *SaveQueryFavoriteRequest, opts ...grpc.CallOption) (*SaveQueryFavoriteReply, error)
	ListQueryFavorites(ctx context.Context, in *ListQueryFavoritesRequest, opts ...grpc.CallOption) (*ListQueryFavoritesReply, error)
	DeleteQueryFavorite(ctx context.Context, in *DeleteQueryFavoriteRequest, opts ...grpc.CallOption) (*DeleteQueryFavoriteReply, error)
	// 告警模板相关接口
	CreateAlertTemplate(ctx context.Context, in *CreateAlertTemplateRequest, opts ...grpc.CallOption) (*CreateAlertTemplateReply, error)
	UpdateAlertTemplate(ctx context.Context, in *UpdateAlertTemplateRequest, opts ...grpc.CallOption) (*UpdateAlertTemplateReply, error)
	DeleteAlertTemplate(ctx context.Context, in *DeleteAlertTemplateRequest, opts ...grpc.CallOption) (*DeleteAlertTemplateReply, error)
	GetAlertTemplate(ctx context.Context, in *GetAlertTemplateRequest, opts ...grpc.CallOption) (*AlertTemplateItem, error)
	ListAlertTemplate(ctx context.Context, in *ListAlertTemplateRequest, opts ...grpc.CallOption) (*ListAlertTemplateReply, error)
	UpdateAlertTemplateStatus(ctx context.Context, in *UpdateAlertTemplateStatusRequest, opts ...grpc.CallOption) (*UpdateAlertTemplateStatusReply, error)
	ApplyAlertTemplate(ctx context.Context, in *ApplyAlertTemplateRequest, opts ...grpc.CallOption) (*ApplyAlertTemplateReply, error)
	// 数据源代理相关接口
	CreateDataSourceProxy(ctx context.Context, in *CreateDataSourceProxyRequest, opts ...grpc.CallOption) (*CreateDataSourceProxyReply, error)
	UpdateDataSourceProxy(ctx context.Context, in *UpdateDataSourceProxyRequest, opts ...grpc.CallOption) (*UpdateDataSourceProxyReply, error)
	DeleteDataSourceProxy(ctx context.Context, in *DeleteDataSourceProxyRequest, opts ...grpc.CallOption) (*DeleteDataSourceProxyReply, error)
	GetDataSourceProxy(ctx context.Context, in *GetDataSourceProxyRequest, opts ...grpc.CallOption) (*DataSourceProxyItem, error)
	ListDataSourceProxy(ctx context.Context, in *ListDataSourceProxyRequest, opts ...grpc.CallOption) (*ListDataSourceProxyReply, error)
	// 元数据管理相关接口
	ListDataSourceMetadata(ctx context.Context, in *ListDataSourceMetadataRequest, opts ...grpc.CallOption) (*ListDataSourceMetadataReply, error)
	GetDataSourceMetadata(ctx context.Context, in *GetDataSourceMetadataRequest, opts ...grpc.CallOption) (*DataSourceMetadataItem, error)
	RefreshDataSourceMetadata(ctx context.Context, in *RefreshDataSourceMetadataRequest, opts ...grpc.CallOption) (*RefreshDataSourceMetadataReply, error)
}

type dataSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSourceClient(cc grpc.ClientConnInterface) DataSourceClient {
	return &dataSourceClient{cc}
}

func (c *dataSourceClient) CreateDataSource(ctx context.Context, in *CreateDataSourceRequest, opts ...grpc.CallOption) (*CreateDataSourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDataSourceReply)
	err := c.cc.Invoke(ctx, DataSource_CreateDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) UpdateDataSource(ctx context.Context, in *UpdateDataSourceRequest, opts ...grpc.CallOption) (*UpdateDataSourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDataSourceReply)
	err := c.cc.Invoke(ctx, DataSource_UpdateDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) UpdateDataSourceStatus(ctx context.Context, in *UpdateDataSourceStatusRequest, opts ...grpc.CallOption) (*UpdateDataSourceStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDataSourceStatusReply)
	err := c.cc.Invoke(ctx, DataSource_UpdateDataSourceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) DeleteDataSource(ctx context.Context, in *DeleteDataSourceRequest, opts ...grpc.CallOption) (*DeleteDataSourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDataSourceReply)
	err := c.cc.Invoke(ctx, DataSource_DeleteDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSourceItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceItem)
	err := c.cc.Invoke(ctx, DataSource_GetDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) ListDataSource(ctx context.Context, in *ListDataSourceRequest, opts ...grpc.CallOption) (*ListDataSourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataSourceReply)
	err := c.cc.Invoke(ctx, DataSource_ListDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) SelectDataSource(ctx context.Context, in *SelectDataSourceRequest, opts ...grpc.CallOption) (*SelectDataSourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectDataSourceReply)
	err := c.cc.Invoke(ctx, DataSource_SelectDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionReply)
	err := c.cc.Invoke(ctx, DataSource_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) QueryDataSource(ctx context.Context, in *QueryDataSourceRequest, opts ...grpc.CallOption) (*QueryDataSourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDataSourceReply)
	err := c.cc.Invoke(ctx, DataSource_QueryDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) ListQueryHistory(ctx context.Context, in *ListQueryHistoryRequest, opts ...grpc.CallOption) (*ListQueryHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQueryHistoryReply)
	err := c.cc.Invoke(ctx, DataSource_ListQueryHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) SaveQueryFavorite(ctx context.Context, in *SaveQueryFavoriteRequest, opts ...grpc.CallOption) (*SaveQueryFavoriteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveQueryFavoriteReply)
	err := c.cc.Invoke(ctx, DataSource_SaveQueryFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) ListQueryFavorites(ctx context.Context, in *ListQueryFavoritesRequest, opts ...grpc.CallOption) (*ListQueryFavoritesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQueryFavoritesReply)
	err := c.cc.Invoke(ctx, DataSource_ListQueryFavorites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) DeleteQueryFavorite(ctx context.Context, in *DeleteQueryFavoriteRequest, opts ...grpc.CallOption) (*DeleteQueryFavoriteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteQueryFavoriteReply)
	err := c.cc.Invoke(ctx, DataSource_DeleteQueryFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) CreateAlertTemplate(ctx context.Context, in *CreateAlertTemplateRequest, opts ...grpc.CallOption) (*CreateAlertTemplateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAlertTemplateReply)
	err := c.cc.Invoke(ctx, DataSource_CreateAlertTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) UpdateAlertTemplate(ctx context.Context, in *UpdateAlertTemplateRequest, opts ...grpc.CallOption) (*UpdateAlertTemplateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAlertTemplateReply)
	err := c.cc.Invoke(ctx, DataSource_UpdateAlertTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) DeleteAlertTemplate(ctx context.Context, in *DeleteAlertTemplateRequest, opts ...grpc.CallOption) (*DeleteAlertTemplateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAlertTemplateReply)
	err := c.cc.Invoke(ctx, DataSource_DeleteAlertTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) GetAlertTemplate(ctx context.Context, in *GetAlertTemplateRequest, opts ...grpc.CallOption) (*AlertTemplateItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertTemplateItem)
	err := c.cc.Invoke(ctx, DataSource_GetAlertTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) ListAlertTemplate(ctx context.Context, in *ListAlertTemplateRequest, opts ...grpc.CallOption) (*ListAlertTemplateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertTemplateReply)
	err := c.cc.Invoke(ctx, DataSource_ListAlertTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) UpdateAlertTemplateStatus(ctx context.Context, in *UpdateAlertTemplateStatusRequest, opts ...grpc.CallOption) (*UpdateAlertTemplateStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAlertTemplateStatusReply)
	err := c.cc.Invoke(ctx, DataSource_UpdateAlertTemplateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) ApplyAlertTemplate(ctx context.Context, in *ApplyAlertTemplateRequest, opts ...grpc.CallOption) (*ApplyAlertTemplateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyAlertTemplateReply)
	err := c.cc.Invoke(ctx, DataSource_ApplyAlertTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) CreateDataSourceProxy(ctx context.Context, in *CreateDataSourceProxyRequest, opts ...grpc.CallOption) (*CreateDataSourceProxyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDataSourceProxyReply)
	err := c.cc.Invoke(ctx, DataSource_CreateDataSourceProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) UpdateDataSourceProxy(ctx context.Context, in *UpdateDataSourceProxyRequest, opts ...grpc.CallOption) (*UpdateDataSourceProxyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDataSourceProxyReply)
	err := c.cc.Invoke(ctx, DataSource_UpdateDataSourceProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) DeleteDataSourceProxy(ctx context.Context, in *DeleteDataSourceProxyRequest, opts ...grpc.CallOption) (*DeleteDataSourceProxyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDataSourceProxyReply)
	err := c.cc.Invoke(ctx, DataSource_DeleteDataSourceProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) GetDataSourceProxy(ctx context.Context, in *GetDataSourceProxyRequest, opts ...grpc.CallOption) (*DataSourceProxyItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceProxyItem)
	err := c.cc.Invoke(ctx, DataSource_GetDataSourceProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) ListDataSourceProxy(ctx context.Context, in *ListDataSourceProxyRequest, opts ...grpc.CallOption) (*ListDataSourceProxyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataSourceProxyReply)
	err := c.cc.Invoke(ctx, DataSource_ListDataSourceProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) ListDataSourceMetadata(ctx context.Context, in *ListDataSourceMetadataRequest, opts ...grpc.CallOption) (*ListDataSourceMetadataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataSourceMetadataReply)
	err := c.cc.Invoke(ctx, DataSource_ListDataSourceMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) GetDataSourceMetadata(ctx context.Context, in *GetDataSourceMetadataRequest, opts ...grpc.CallOption) (*DataSourceMetadataItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceMetadataItem)
	err := c.cc.Invoke(ctx, DataSource_GetDataSourceMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) RefreshDataSourceMetadata(ctx context.Context, in *RefreshDataSourceMetadataRequest, opts ...grpc.CallOption) (*RefreshDataSourceMetadataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshDataSourceMetadataReply)
	err := c.cc.Invoke(ctx, DataSource_RefreshDataSourceMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSourceServer is the server API for DataSource service.
// All implementations must embed UnimplementedDataSourceServer
// for forward compatibility.
type DataSourceServer interface {
	CreateDataSource(context.Context, *CreateDataSourceRequest) (*CreateDataSourceReply, error)
	UpdateDataSource(context.Context, *UpdateDataSourceRequest) (*UpdateDataSourceReply, error)
	UpdateDataSourceStatus(context.Context, *UpdateDataSourceStatusRequest) (*UpdateDataSourceStatusReply, error)
	DeleteDataSource(context.Context, *DeleteDataSourceRequest) (*DeleteDataSourceReply, error)
	GetDataSource(context.Context, *GetDataSourceRequest) (*DataSourceItem, error)
	ListDataSource(context.Context, *ListDataSourceRequest) (*ListDataSourceReply, error)
	SelectDataSource(context.Context, *SelectDataSourceRequest) (*SelectDataSourceReply, error)
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionReply, error)
	// 及时查询相关接口
	QueryDataSource(context.Context, *QueryDataSourceRequest) (*QueryDataSourceReply, error)
	ListQueryHistory(context.Context, *ListQueryHistoryRequest) (*ListQueryHistoryReply, error)
	SaveQueryFavorite(context.Context, *SaveQueryFavoriteRequest) (*SaveQueryFavoriteReply, error)
	ListQueryFavorites(context.Context, *ListQueryFavoritesRequest) (*ListQueryFavoritesReply, error)
	DeleteQueryFavorite(context.Context, *DeleteQueryFavoriteRequest) (*DeleteQueryFavoriteReply, error)
	// 告警模板相关接口
	CreateAlertTemplate(context.Context, *CreateAlertTemplateRequest) (*CreateAlertTemplateReply, error)
	UpdateAlertTemplate(context.Context, *UpdateAlertTemplateRequest) (*UpdateAlertTemplateReply, error)
	DeleteAlertTemplate(context.Context, *DeleteAlertTemplateRequest) (*DeleteAlertTemplateReply, error)
	GetAlertTemplate(context.Context, *GetAlertTemplateRequest) (*AlertTemplateItem, error)
	ListAlertTemplate(context.Context, *ListAlertTemplateRequest) (*ListAlertTemplateReply, error)
	UpdateAlertTemplateStatus(context.Context, *UpdateAlertTemplateStatusRequest) (*UpdateAlertTemplateStatusReply, error)
	ApplyAlertTemplate(context.Context, *ApplyAlertTemplateRequest) (*ApplyAlertTemplateReply, error)
	// 数据源代理相关接口
	CreateDataSourceProxy(context.Context, *CreateDataSourceProxyRequest) (*CreateDataSourceProxyReply, error)
	UpdateDataSourceProxy(context.Context, *UpdateDataSourceProxyRequest) (*UpdateDataSourceProxyReply, error)
	DeleteDataSourceProxy(context.Context, *DeleteDataSourceProxyRequest) (*DeleteDataSourceProxyReply, error)
	GetDataSourceProxy(context.Context, *GetDataSourceProxyRequest) (*DataSourceProxyItem, error)
	ListDataSourceProxy(context.Context, *ListDataSourceProxyRequest) (*ListDataSourceProxyReply, error)
	// 元数据管理相关接口
	ListDataSourceMetadata(context.Context, *ListDataSourceMetadataRequest) (*ListDataSourceMetadataReply, error)
	GetDataSourceMetadata(context.Context, *GetDataSourceMetadataRequest) (*DataSourceMetadataItem, error)
	RefreshDataSourceMetadata(context.Context, *RefreshDataSourceMetadataRequest) (*RefreshDataSourceMetadataReply, error)
	mustEmbedUnimplementedDataSourceServer()
}

// UnimplementedDataSourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSourceServer struct{}

func (UnimplementedDataSourceServer) CreateDataSource(context.Context, *CreateDataSourceRequest) (*CreateDataSourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataSource not implemented")
}
func (UnimplementedDataSourceServer) UpdateDataSource(context.Context, *UpdateDataSourceRequest) (*UpdateDataSourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDataSource not implemented")
}
func (UnimplementedDataSourceServer) UpdateDataSourceStatus(context.Context, *UpdateDataSourceStatusRequest) (*UpdateDataSourceStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDataSourceStatus not implemented")
}
func (UnimplementedDataSourceServer) DeleteDataSource(context.Context, *DeleteDataSourceRequest) (*DeleteDataSourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDataSource not implemented")
}
func (UnimplementedDataSourceServer) GetDataSource(context.Context, *GetDataSourceRequest) (*DataSourceItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataSource not implemented")
}
func (UnimplementedDataSourceServer) ListDataSource(context.Context, *ListDataSourceRequest) (*ListDataSourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDataSource not implemented")
}
func (UnimplementedDataSourceServer) SelectDataSource(context.Context, *SelectDataSourceRequest) (*SelectDataSourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectDataSource not implemented")
}
func (UnimplementedDataSourceServer) TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedDataSourceServer) QueryDataSource(context.Context, *QueryDataSourceRequest) (*QueryDataSourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDataSource not implemented")
}
func (UnimplementedDataSourceServer) ListQueryHistory(context.Context, *ListQueryHistoryRequest) (*ListQueryHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueryHistory not implemented")
}
func (UnimplementedDataSourceServer) SaveQueryFavorite(context.Context, *SaveQueryFavoriteRequest) (*SaveQueryFavoriteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveQueryFavorite not implemented")
}
func (UnimplementedDataSourceServer) ListQueryFavorites(context.Context, *ListQueryFavoritesRequest) (*ListQueryFavoritesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueryFavorites not implemented")
}
func (UnimplementedDataSourceServer) DeleteQueryFavorite(context.Context, *DeleteQueryFavoriteRequest) (*DeleteQueryFavoriteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQueryFavorite not implemented")
}
func (UnimplementedDataSourceServer) CreateAlertTemplate(context.Context, *CreateAlertTemplateRequest) (*CreateAlertTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlertTemplate not implemented")
}
func (UnimplementedDataSourceServer) UpdateAlertTemplate(context.Context, *UpdateAlertTemplateRequest) (*UpdateAlertTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlertTemplate not implemented")
}
func (UnimplementedDataSourceServer) DeleteAlertTemplate(context.Context, *DeleteAlertTemplateRequest) (*DeleteAlertTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlertTemplate not implemented")
}
func (UnimplementedDataSourceServer) GetAlertTemplate(context.Context, *GetAlertTemplateRequest) (*AlertTemplateItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertTemplate not implemented")
}
func (UnimplementedDataSourceServer) ListAlertTemplate(context.Context, *ListAlertTemplateRequest) (*ListAlertTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlertTemplate not implemented")
}
func (UnimplementedDataSourceServer) UpdateAlertTemplateStatus(context.Context, *UpdateAlertTemplateStatusRequest) (*UpdateAlertTemplateStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlertTemplateStatus not implemented")
}
func (UnimplementedDataSourceServer) ApplyAlertTemplate(context.Context, *ApplyAlertTemplateRequest) (*ApplyAlertTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyAlertTemplate not implemented")
}
func (UnimplementedDataSourceServer) CreateDataSourceProxy(context.Context, *CreateDataSourceProxyRequest) (*CreateDataSourceProxyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataSourceProxy not implemented")
}
func (UnimplementedDataSourceServer) UpdateDataSourceProxy(context.Context, *UpdateDataSourceProxyRequest) (*UpdateDataSourceProxyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDataSourceProxy not implemented")
}
func (UnimplementedDataSourceServer) DeleteDataSourceProxy(context.Context, *DeleteDataSourceProxyRequest) (*DeleteDataSourceProxyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDataSourceProxy not implemented")
}
func (UnimplementedDataSourceServer) GetDataSourceProxy(context.Context, *GetDataSourceProxyRequest) (*DataSourceProxyItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataSourceProxy not implemented")
}
func (UnimplementedDataSourceServer) ListDataSourceProxy(context.Context, *ListDataSourceProxyRequest) (*ListDataSourceProxyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDataSourceProxy not implemented")
}
func (UnimplementedDataSourceServer) ListDataSourceMetadata(context.Context, *ListDataSourceMetadataRequest) (*ListDataSourceMetadataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDataSourceMetadata not implemented")
}
func (UnimplementedDataSourceServer) GetDataSourceMetadata(context.Context, *GetDataSourceMetadataRequest) (*DataSourceMetadataItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataSourceMetadata not implemented")
}
func (UnimplementedDataSourceServer) RefreshDataSourceMetadata(context.Context, *RefreshDataSourceMetadataRequest) (*RefreshDataSourceMetadataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshDataSourceMetadata not implemented")
}
func (UnimplementedDataSourceServer) mustEmbedUnimplementedDataSourceServer() {}
func (UnimplementedDataSourceServer) testEmbeddedByValue()                    {}

// UnsafeDataSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSourceServer will
// result in compilation errors.
type UnsafeDataSourceServer interface {
	mustEmbedUnimplementedDataSourceServer()
}

func RegisterDataSourceServer(s grpc.ServiceRegistrar, srv DataSourceServer) {
	// If the following call pancis, it indicates UnimplementedDataSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSource_ServiceDesc, srv)
}

func _DataSource_CreateDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).CreateDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_CreateDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).CreateDataSource(ctx, req.(*CreateDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_UpdateDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).UpdateDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_UpdateDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).UpdateDataSource(ctx, req.(*UpdateDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_UpdateDataSourceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataSourceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).UpdateDataSourceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_UpdateDataSourceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).UpdateDataSourceStatus(ctx, req.(*UpdateDataSourceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_DeleteDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).DeleteDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_DeleteDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).DeleteDataSource(ctx, req.(*DeleteDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_GetDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).GetDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_GetDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).GetDataSource(ctx, req.(*GetDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_ListDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).ListDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_ListDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).ListDataSource(ctx, req.(*ListDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_SelectDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).SelectDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_SelectDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).SelectDataSource(ctx, req.(*SelectDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_QueryDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).QueryDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_QueryDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).QueryDataSource(ctx, req.(*QueryDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_ListQueryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).ListQueryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_ListQueryHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).ListQueryHistory(ctx, req.(*ListQueryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_SaveQueryFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveQueryFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).SaveQueryFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_SaveQueryFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).SaveQueryFavorite(ctx, req.(*SaveQueryFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_ListQueryFavorites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueryFavoritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).ListQueryFavorites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_ListQueryFavorites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).ListQueryFavorites(ctx, req.(*ListQueryFavoritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_DeleteQueryFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQueryFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).DeleteQueryFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_DeleteQueryFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).DeleteQueryFavorite(ctx, req.(*DeleteQueryFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_CreateAlertTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).CreateAlertTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_CreateAlertTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).CreateAlertTemplate(ctx, req.(*CreateAlertTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_UpdateAlertTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlertTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).UpdateAlertTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_UpdateAlertTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).UpdateAlertTemplate(ctx, req.(*UpdateAlertTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_DeleteAlertTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlertTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).DeleteAlertTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_DeleteAlertTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).DeleteAlertTemplate(ctx, req.(*DeleteAlertTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_GetAlertTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).GetAlertTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_GetAlertTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).GetAlertTemplate(ctx, req.(*GetAlertTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_ListAlertTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).ListAlertTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_ListAlertTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).ListAlertTemplate(ctx, req.(*ListAlertTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_UpdateAlertTemplateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlertTemplateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).UpdateAlertTemplateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_UpdateAlertTemplateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).UpdateAlertTemplateStatus(ctx, req.(*UpdateAlertTemplateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_ApplyAlertTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyAlertTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).ApplyAlertTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_ApplyAlertTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).ApplyAlertTemplate(ctx, req.(*ApplyAlertTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_CreateDataSourceProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataSourceProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).CreateDataSourceProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_CreateDataSourceProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).CreateDataSourceProxy(ctx, req.(*CreateDataSourceProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_UpdateDataSourceProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataSourceProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).UpdateDataSourceProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_UpdateDataSourceProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).UpdateDataSourceProxy(ctx, req.(*UpdateDataSourceProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_DeleteDataSourceProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataSourceProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).DeleteDataSourceProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_DeleteDataSourceProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).DeleteDataSourceProxy(ctx, req.(*DeleteDataSourceProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_GetDataSourceProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataSourceProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).GetDataSourceProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_GetDataSourceProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).GetDataSourceProxy(ctx, req.(*GetDataSourceProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_ListDataSourceProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataSourceProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).ListDataSourceProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_ListDataSourceProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).ListDataSourceProxy(ctx, req.(*ListDataSourceProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_ListDataSourceMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataSourceMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).ListDataSourceMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_ListDataSourceMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).ListDataSourceMetadata(ctx, req.(*ListDataSourceMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_GetDataSourceMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataSourceMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).GetDataSourceMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_GetDataSourceMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).GetDataSourceMetadata(ctx, req.(*GetDataSourceMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSource_RefreshDataSourceMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshDataSourceMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServer).RefreshDataSourceMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSource_RefreshDataSourceMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServer).RefreshDataSourceMetadata(ctx, req.(*RefreshDataSourceMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataSource_ServiceDesc is the grpc.ServiceDesc for DataSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereign.api.v1.DataSource",
	HandlerType: (*DataSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDataSource",
			Handler:    _DataSource_CreateDataSource_Handler,
		},
		{
			MethodName: "UpdateDataSource",
			Handler:    _DataSource_UpdateDataSource_Handler,
		},
		{
			MethodName: "UpdateDataSourceStatus",
			Handler:    _DataSource_UpdateDataSourceStatus_Handler,
		},
		{
			MethodName: "DeleteDataSource",
			Handler:    _DataSource_DeleteDataSource_Handler,
		},
		{
			MethodName: "GetDataSource",
			Handler:    _DataSource_GetDataSource_Handler,
		},
		{
			MethodName: "ListDataSource",
			Handler:    _DataSource_ListDataSource_Handler,
		},
		{
			MethodName: "SelectDataSource",
			Handler:    _DataSource_SelectDataSource_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _DataSource_TestConnection_Handler,
		},
		{
			MethodName: "QueryDataSource",
			Handler:    _DataSource_QueryDataSource_Handler,
		},
		{
			MethodName: "ListQueryHistory",
			Handler:    _DataSource_ListQueryHistory_Handler,
		},
		{
			MethodName: "SaveQueryFavorite",
			Handler:    _DataSource_SaveQueryFavorite_Handler,
		},
		{
			MethodName: "ListQueryFavorites",
			Handler:    _DataSource_ListQueryFavorites_Handler,
		},
		{
			MethodName: "DeleteQueryFavorite",
			Handler:    _DataSource_DeleteQueryFavorite_Handler,
		},
		{
			MethodName: "CreateAlertTemplate",
			Handler:    _DataSource_CreateAlertTemplate_Handler,
		},
		{
			MethodName: "UpdateAlertTemplate",
			Handler:    _DataSource_UpdateAlertTemplate_Handler,
		},
		{
			MethodName: "DeleteAlertTemplate",
			Handler:    _DataSource_DeleteAlertTemplate_Handler,
		},
		{
			MethodName: "GetAlertTemplate",
			Handler:    _DataSource_GetAlertTemplate_Handler,
		},
		{
			MethodName: "ListAlertTemplate",
			Handler:    _DataSource_ListAlertTemplate_Handler,
		},
		{
			MethodName: "UpdateAlertTemplateStatus",
			Handler:    _DataSource_UpdateAlertTemplateStatus_Handler,
		},
		{
			MethodName: "ApplyAlertTemplate",
			Handler:    _DataSource_ApplyAlertTemplate_Handler,
		},
		{
			MethodName: "CreateDataSourceProxy",
			Handler:    _DataSource_CreateDataSourceProxy_Handler,
		},
		{
			MethodName: "UpdateDataSourceProxy",
			Handler:    _DataSource_UpdateDataSourceProxy_Handler,
		},
		{
			MethodName: "DeleteDataSourceProxy",
			Handler:    _DataSource_DeleteDataSourceProxy_Handler,
		},
		{
			MethodName: "GetDataSourceProxy",
			Handler:    _DataSource_GetDataSourceProxy_Handler,
		},
		{
			MethodName: "ListDataSourceProxy",
			Handler:    _DataSource_ListDataSourceProxy_Handler,
		},
		{
			MethodName: "ListDataSourceMetadata",
			Handler:    _DataSource_ListDataSourceMetadata_Handler,
		},
		{
			MethodName: "GetDataSourceMetadata",
			Handler:    _DataSource_GetDataSourceMetadata_Handler,
		},
		{
			MethodName: "RefreshDataSourceMetadata",
			Handler:    _DataSource_RefreshDataSourceMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/datasource.proto",
}
