// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.32.1
// source: api/v1/event.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEventCenterGetAlertEventChart = "/sovereign.api.v1.EventCenter/GetAlertEventChart"
const OperationEventCenterGetAlertEventReport = "/sovereign.api.v1.EventCenter/GetAlertEventReport"
const OperationEventCenterGetAlertHistory = "/sovereign.api.v1.EventCenter/GetAlertHistory"
const OperationEventCenterGetAlertRawData = "/sovereign.api.v1.EventCenter/GetAlertRawData"
const OperationEventCenterGetRealtimeAlert = "/sovereign.api.v1.EventCenter/GetRealtimeAlert"
const OperationEventCenterGetScheduledTask = "/sovereign.api.v1.EventCenter/GetScheduledTask"
const OperationEventCenterInterveneAlert = "/sovereign.api.v1.EventCenter/InterveneAlert"
const OperationEventCenterListAlertHistory = "/sovereign.api.v1.EventCenter/ListAlertHistory"
const OperationEventCenterListNotificationHistory = "/sovereign.api.v1.EventCenter/ListNotificationHistory"
const OperationEventCenterListRealtimeAlerts = "/sovereign.api.v1.EventCenter/ListRealtimeAlerts"
const OperationEventCenterListScheduledTasks = "/sovereign.api.v1.EventCenter/ListScheduledTasks"
const OperationEventCenterPushExternalAlert = "/sovereign.api.v1.EventCenter/PushExternalAlert"
const OperationEventCenterPushInternalAlert = "/sovereign.api.v1.EventCenter/PushInternalAlert"
const OperationEventCenterRetryNotification = "/sovereign.api.v1.EventCenter/RetryNotification"
const OperationEventCenterSuppressAlert = "/sovereign.api.v1.EventCenter/SuppressAlert"
const OperationEventCenterUpdateScheduledTaskStatus = "/sovereign.api.v1.EventCenter/UpdateScheduledTaskStatus"
const OperationEventCenterUpgradeAlert = "/sovereign.api.v1.EventCenter/UpgradeAlert"

type EventCenterHTTPServer interface {
	GetAlertEventChart(context.Context, *GetAlertEventChartRequest) (*GetAlertEventChartReply, error)
	GetAlertEventReport(context.Context, *GetAlertEventReportRequest) (*GetAlertEventReportReply, error)
	GetAlertHistory(context.Context, *GetAlertHistoryRequest) (*AlertHistoryItem, error)
	GetAlertRawData(context.Context, *GetAlertRawDataRequest) (*GetAlertRawDataReply, error)
	GetRealtimeAlert(context.Context, *GetRealtimeAlertRequest) (*RealtimeAlertItem, error)
	GetScheduledTask(context.Context, *GetScheduledTaskRequest) (*ScheduledTaskItem, error)
	InterveneAlert(context.Context, *InterveneAlertRequest) (*InterveneAlertReply, error)
	// ListAlertHistory 告警历史相关接口
	ListAlertHistory(context.Context, *ListAlertHistoryRequest) (*ListAlertHistoryReply, error)
	// ListNotificationHistory 通知历史相关接口
	ListNotificationHistory(context.Context, *ListNotificationHistoryRequest) (*ListNotificationHistoryReply, error)
	// ListRealtimeAlerts 实时告警相关接口
	ListRealtimeAlerts(context.Context, *ListRealtimeAlertsRequest) (*ListRealtimeAlertsReply, error)
	// ListScheduledTasks 定时任务相关接口
	ListScheduledTasks(context.Context, *ListScheduledTasksRequest) (*ListScheduledTasksReply, error)
	// PushExternalAlert 事件总线相关接口
	PushExternalAlert(context.Context, *PushExternalAlertRequest) (*PushExternalAlertReply, error)
	PushInternalAlert(context.Context, *PushInternalAlertRequest) (*PushInternalAlertReply, error)
	RetryNotification(context.Context, *RetryNotificationRequest) (*RetryNotificationReply, error)
	SuppressAlert(context.Context, *SuppressAlertRequest) (*SuppressAlertReply, error)
	UpdateScheduledTaskStatus(context.Context, *UpdateScheduledTaskStatusRequest) (*UpdateScheduledTaskStatusReply, error)
	UpgradeAlert(context.Context, *UpgradeAlertRequest) (*UpgradeAlertReply, error)
}

func RegisterEventCenterHTTPServer(s *http.Server, srv EventCenterHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/alerts/realtime", _EventCenter_ListRealtimeAlerts0_HTTP_Handler(srv))
	r.GET("/v1/alert/realtime/{uid}", _EventCenter_GetRealtimeAlert0_HTTP_Handler(srv))
	r.POST("/v1/alert/{uid}/intervene", _EventCenter_InterveneAlert0_HTTP_Handler(srv))
	r.POST("/v1/alert/{uid}/suppress", _EventCenter_SuppressAlert0_HTTP_Handler(srv))
	r.POST("/v1/alert/{uid}/upgrade", _EventCenter_UpgradeAlert0_HTTP_Handler(srv))
	r.GET("/v1/alert/{uid}/event-chart", _EventCenter_GetAlertEventChart0_HTTP_Handler(srv))
	r.GET("/v1/alerts/history", _EventCenter_ListAlertHistory0_HTTP_Handler(srv))
	r.GET("/v1/alert/history/{uid}", _EventCenter_GetAlertHistory0_HTTP_Handler(srv))
	r.GET("/v1/alert/{uid}/raw-data", _EventCenter_GetAlertRawData0_HTTP_Handler(srv))
	r.GET("/v1/alert/{uid}/event-report", _EventCenter_GetAlertEventReport0_HTTP_Handler(srv))
	r.GET("/v1/notifications/history", _EventCenter_ListNotificationHistory0_HTTP_Handler(srv))
	r.POST("/v1/notification/{uid}/retry", _EventCenter_RetryNotification0_HTTP_Handler(srv))
	r.POST("/v1/event/external/alert", _EventCenter_PushExternalAlert0_HTTP_Handler(srv))
	r.POST("/v1/event/internal/alert", _EventCenter_PushInternalAlert0_HTTP_Handler(srv))
	r.GET("/v1/scheduled-tasks", _EventCenter_ListScheduledTasks0_HTTP_Handler(srv))
	r.GET("/v1/scheduled-task/{uid}", _EventCenter_GetScheduledTask0_HTTP_Handler(srv))
	r.PUT("/v1/scheduled-task/{uid}/status", _EventCenter_UpdateScheduledTaskStatus0_HTTP_Handler(srv))
}

func _EventCenter_ListRealtimeAlerts0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRealtimeAlertsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterListRealtimeAlerts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRealtimeAlerts(ctx, req.(*ListRealtimeAlertsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRealtimeAlertsReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_GetRealtimeAlert0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRealtimeAlertRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterGetRealtimeAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRealtimeAlert(ctx, req.(*GetRealtimeAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RealtimeAlertItem)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_InterveneAlert0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InterveneAlertRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterInterveneAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InterveneAlert(ctx, req.(*InterveneAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InterveneAlertReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_SuppressAlert0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SuppressAlertRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterSuppressAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SuppressAlert(ctx, req.(*SuppressAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SuppressAlertReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_UpgradeAlert0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpgradeAlertRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterUpgradeAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpgradeAlert(ctx, req.(*UpgradeAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpgradeAlertReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_GetAlertEventChart0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAlertEventChartRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterGetAlertEventChart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAlertEventChart(ctx, req.(*GetAlertEventChartRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAlertEventChartReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_ListAlertHistory0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAlertHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterListAlertHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAlertHistory(ctx, req.(*ListAlertHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAlertHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_GetAlertHistory0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAlertHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterGetAlertHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAlertHistory(ctx, req.(*GetAlertHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AlertHistoryItem)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_GetAlertRawData0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAlertRawDataRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterGetAlertRawData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAlertRawData(ctx, req.(*GetAlertRawDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAlertRawDataReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_GetAlertEventReport0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAlertEventReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterGetAlertEventReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAlertEventReport(ctx, req.(*GetAlertEventReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAlertEventReportReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_ListNotificationHistory0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNotificationHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterListNotificationHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNotificationHistory(ctx, req.(*ListNotificationHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNotificationHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_RetryNotification0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RetryNotificationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterRetryNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RetryNotification(ctx, req.(*RetryNotificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RetryNotificationReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_PushExternalAlert0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PushExternalAlertRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterPushExternalAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PushExternalAlert(ctx, req.(*PushExternalAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PushExternalAlertReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_PushInternalAlert0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PushInternalAlertRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterPushInternalAlert)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PushInternalAlert(ctx, req.(*PushInternalAlertRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PushInternalAlertReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_ListScheduledTasks0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListScheduledTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterListScheduledTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListScheduledTasks(ctx, req.(*ListScheduledTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListScheduledTasksReply)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_GetScheduledTask0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetScheduledTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterGetScheduledTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetScheduledTask(ctx, req.(*GetScheduledTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ScheduledTaskItem)
		return ctx.Result(200, reply)
	}
}

func _EventCenter_UpdateScheduledTaskStatus0_HTTP_Handler(srv EventCenterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateScheduledTaskStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventCenterUpdateScheduledTaskStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateScheduledTaskStatus(ctx, req.(*UpdateScheduledTaskStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateScheduledTaskStatusReply)
		return ctx.Result(200, reply)
	}
}

type EventCenterHTTPClient interface {
	GetAlertEventChart(ctx context.Context, req *GetAlertEventChartRequest, opts ...http.CallOption) (rsp *GetAlertEventChartReply, err error)
	GetAlertEventReport(ctx context.Context, req *GetAlertEventReportRequest, opts ...http.CallOption) (rsp *GetAlertEventReportReply, err error)
	GetAlertHistory(ctx context.Context, req *GetAlertHistoryRequest, opts ...http.CallOption) (rsp *AlertHistoryItem, err error)
	GetAlertRawData(ctx context.Context, req *GetAlertRawDataRequest, opts ...http.CallOption) (rsp *GetAlertRawDataReply, err error)
	GetRealtimeAlert(ctx context.Context, req *GetRealtimeAlertRequest, opts ...http.CallOption) (rsp *RealtimeAlertItem, err error)
	GetScheduledTask(ctx context.Context, req *GetScheduledTaskRequest, opts ...http.CallOption) (rsp *ScheduledTaskItem, err error)
	InterveneAlert(ctx context.Context, req *InterveneAlertRequest, opts ...http.CallOption) (rsp *InterveneAlertReply, err error)
	// ListAlertHistory 告警历史相关接口
	ListAlertHistory(ctx context.Context, req *ListAlertHistoryRequest, opts ...http.CallOption) (rsp *ListAlertHistoryReply, err error)
	// ListNotificationHistory 通知历史相关接口
	ListNotificationHistory(ctx context.Context, req *ListNotificationHistoryRequest, opts ...http.CallOption) (rsp *ListNotificationHistoryReply, err error)
	// ListRealtimeAlerts 实时告警相关接口
	ListRealtimeAlerts(ctx context.Context, req *ListRealtimeAlertsRequest, opts ...http.CallOption) (rsp *ListRealtimeAlertsReply, err error)
	// ListScheduledTasks 定时任务相关接口
	ListScheduledTasks(ctx context.Context, req *ListScheduledTasksRequest, opts ...http.CallOption) (rsp *ListScheduledTasksReply, err error)
	// PushExternalAlert 事件总线相关接口
	PushExternalAlert(ctx context.Context, req *PushExternalAlertRequest, opts ...http.CallOption) (rsp *PushExternalAlertReply, err error)
	PushInternalAlert(ctx context.Context, req *PushInternalAlertRequest, opts ...http.CallOption) (rsp *PushInternalAlertReply, err error)
	RetryNotification(ctx context.Context, req *RetryNotificationRequest, opts ...http.CallOption) (rsp *RetryNotificationReply, err error)
	SuppressAlert(ctx context.Context, req *SuppressAlertRequest, opts ...http.CallOption) (rsp *SuppressAlertReply, err error)
	UpdateScheduledTaskStatus(ctx context.Context, req *UpdateScheduledTaskStatusRequest, opts ...http.CallOption) (rsp *UpdateScheduledTaskStatusReply, err error)
	UpgradeAlert(ctx context.Context, req *UpgradeAlertRequest, opts ...http.CallOption) (rsp *UpgradeAlertReply, err error)
}

type EventCenterHTTPClientImpl struct {
	cc *http.Client
}

func NewEventCenterHTTPClient(client *http.Client) EventCenterHTTPClient {
	return &EventCenterHTTPClientImpl{client}
}

func (c *EventCenterHTTPClientImpl) GetAlertEventChart(ctx context.Context, in *GetAlertEventChartRequest, opts ...http.CallOption) (*GetAlertEventChartReply, error) {
	var out GetAlertEventChartReply
	pattern := "/v1/alert/{uid}/event-chart"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterGetAlertEventChart))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) GetAlertEventReport(ctx context.Context, in *GetAlertEventReportRequest, opts ...http.CallOption) (*GetAlertEventReportReply, error) {
	var out GetAlertEventReportReply
	pattern := "/v1/alert/{uid}/event-report"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterGetAlertEventReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) GetAlertHistory(ctx context.Context, in *GetAlertHistoryRequest, opts ...http.CallOption) (*AlertHistoryItem, error) {
	var out AlertHistoryItem
	pattern := "/v1/alert/history/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterGetAlertHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) GetAlertRawData(ctx context.Context, in *GetAlertRawDataRequest, opts ...http.CallOption) (*GetAlertRawDataReply, error) {
	var out GetAlertRawDataReply
	pattern := "/v1/alert/{uid}/raw-data"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterGetAlertRawData))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) GetRealtimeAlert(ctx context.Context, in *GetRealtimeAlertRequest, opts ...http.CallOption) (*RealtimeAlertItem, error) {
	var out RealtimeAlertItem
	pattern := "/v1/alert/realtime/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterGetRealtimeAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) GetScheduledTask(ctx context.Context, in *GetScheduledTaskRequest, opts ...http.CallOption) (*ScheduledTaskItem, error) {
	var out ScheduledTaskItem
	pattern := "/v1/scheduled-task/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterGetScheduledTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) InterveneAlert(ctx context.Context, in *InterveneAlertRequest, opts ...http.CallOption) (*InterveneAlertReply, error) {
	var out InterveneAlertReply
	pattern := "/v1/alert/{uid}/intervene"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventCenterInterveneAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAlertHistory 告警历史相关接口
func (c *EventCenterHTTPClientImpl) ListAlertHistory(ctx context.Context, in *ListAlertHistoryRequest, opts ...http.CallOption) (*ListAlertHistoryReply, error) {
	var out ListAlertHistoryReply
	pattern := "/v1/alerts/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterListAlertHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNotificationHistory 通知历史相关接口
func (c *EventCenterHTTPClientImpl) ListNotificationHistory(ctx context.Context, in *ListNotificationHistoryRequest, opts ...http.CallOption) (*ListNotificationHistoryReply, error) {
	var out ListNotificationHistoryReply
	pattern := "/v1/notifications/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterListNotificationHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRealtimeAlerts 实时告警相关接口
func (c *EventCenterHTTPClientImpl) ListRealtimeAlerts(ctx context.Context, in *ListRealtimeAlertsRequest, opts ...http.CallOption) (*ListRealtimeAlertsReply, error) {
	var out ListRealtimeAlertsReply
	pattern := "/v1/alerts/realtime"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterListRealtimeAlerts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListScheduledTasks 定时任务相关接口
func (c *EventCenterHTTPClientImpl) ListScheduledTasks(ctx context.Context, in *ListScheduledTasksRequest, opts ...http.CallOption) (*ListScheduledTasksReply, error) {
	var out ListScheduledTasksReply
	pattern := "/v1/scheduled-tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventCenterListScheduledTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PushExternalAlert 事件总线相关接口
func (c *EventCenterHTTPClientImpl) PushExternalAlert(ctx context.Context, in *PushExternalAlertRequest, opts ...http.CallOption) (*PushExternalAlertReply, error) {
	var out PushExternalAlertReply
	pattern := "/v1/event/external/alert"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventCenterPushExternalAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) PushInternalAlert(ctx context.Context, in *PushInternalAlertRequest, opts ...http.CallOption) (*PushInternalAlertReply, error) {
	var out PushInternalAlertReply
	pattern := "/v1/event/internal/alert"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventCenterPushInternalAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) RetryNotification(ctx context.Context, in *RetryNotificationRequest, opts ...http.CallOption) (*RetryNotificationReply, error) {
	var out RetryNotificationReply
	pattern := "/v1/notification/{uid}/retry"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventCenterRetryNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) SuppressAlert(ctx context.Context, in *SuppressAlertRequest, opts ...http.CallOption) (*SuppressAlertReply, error) {
	var out SuppressAlertReply
	pattern := "/v1/alert/{uid}/suppress"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventCenterSuppressAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) UpdateScheduledTaskStatus(ctx context.Context, in *UpdateScheduledTaskStatusRequest, opts ...http.CallOption) (*UpdateScheduledTaskStatusReply, error) {
	var out UpdateScheduledTaskStatusReply
	pattern := "/v1/scheduled-task/{uid}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventCenterUpdateScheduledTaskStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventCenterHTTPClientImpl) UpgradeAlert(ctx context.Context, in *UpgradeAlertRequest, opts ...http.CallOption) (*UpgradeAlertReply, error) {
	var out UpgradeAlertReply
	pattern := "/v1/alert/{uid}/upgrade"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventCenterUpgradeAlert))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
