// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/v1/event.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventCenter_ListRealtimeAlerts_FullMethodName        = "/sovereign.api.v1.EventCenter/ListRealtimeAlerts"
	EventCenter_GetRealtimeAlert_FullMethodName          = "/sovereign.api.v1.EventCenter/GetRealtimeAlert"
	EventCenter_InterveneAlert_FullMethodName            = "/sovereign.api.v1.EventCenter/InterveneAlert"
	EventCenter_SuppressAlert_FullMethodName             = "/sovereign.api.v1.EventCenter/SuppressAlert"
	EventCenter_UpgradeAlert_FullMethodName              = "/sovereign.api.v1.EventCenter/UpgradeAlert"
	EventCenter_GetAlertEventChart_FullMethodName        = "/sovereign.api.v1.EventCenter/GetAlertEventChart"
	EventCenter_ListAlertHistory_FullMethodName          = "/sovereign.api.v1.EventCenter/ListAlertHistory"
	EventCenter_GetAlertHistory_FullMethodName           = "/sovereign.api.v1.EventCenter/GetAlertHistory"
	EventCenter_GetAlertRawData_FullMethodName           = "/sovereign.api.v1.EventCenter/GetAlertRawData"
	EventCenter_GetAlertEventReport_FullMethodName       = "/sovereign.api.v1.EventCenter/GetAlertEventReport"
	EventCenter_ListNotificationHistory_FullMethodName   = "/sovereign.api.v1.EventCenter/ListNotificationHistory"
	EventCenter_RetryNotification_FullMethodName         = "/sovereign.api.v1.EventCenter/RetryNotification"
	EventCenter_PushExternalAlert_FullMethodName         = "/sovereign.api.v1.EventCenter/PushExternalAlert"
	EventCenter_PushInternalAlert_FullMethodName         = "/sovereign.api.v1.EventCenter/PushInternalAlert"
	EventCenter_ListScheduledTasks_FullMethodName        = "/sovereign.api.v1.EventCenter/ListScheduledTasks"
	EventCenter_GetScheduledTask_FullMethodName          = "/sovereign.api.v1.EventCenter/GetScheduledTask"
	EventCenter_UpdateScheduledTaskStatus_FullMethodName = "/sovereign.api.v1.EventCenter/UpdateScheduledTaskStatus"
)

// EventCenterClient is the client API for EventCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 事件中心服务
type EventCenterClient interface {
	// 实时告警相关接口
	ListRealtimeAlerts(ctx context.Context, in *ListRealtimeAlertsRequest, opts ...grpc.CallOption) (*ListRealtimeAlertsReply, error)
	GetRealtimeAlert(ctx context.Context, in *GetRealtimeAlertRequest, opts ...grpc.CallOption) (*RealtimeAlertItem, error)
	InterveneAlert(ctx context.Context, in *InterveneAlertRequest, opts ...grpc.CallOption) (*InterveneAlertReply, error)
	SuppressAlert(ctx context.Context, in *SuppressAlertRequest, opts ...grpc.CallOption) (*SuppressAlertReply, error)
	UpgradeAlert(ctx context.Context, in *UpgradeAlertRequest, opts ...grpc.CallOption) (*UpgradeAlertReply, error)
	GetAlertEventChart(ctx context.Context, in *GetAlertEventChartRequest, opts ...grpc.CallOption) (*GetAlertEventChartReply, error)
	// 告警历史相关接口
	ListAlertHistory(ctx context.Context, in *ListAlertHistoryRequest, opts ...grpc.CallOption) (*ListAlertHistoryReply, error)
	GetAlertHistory(ctx context.Context, in *GetAlertHistoryRequest, opts ...grpc.CallOption) (*AlertHistoryItem, error)
	GetAlertRawData(ctx context.Context, in *GetAlertRawDataRequest, opts ...grpc.CallOption) (*GetAlertRawDataReply, error)
	GetAlertEventReport(ctx context.Context, in *GetAlertEventReportRequest, opts ...grpc.CallOption) (*GetAlertEventReportReply, error)
	// 通知历史相关接口
	ListNotificationHistory(ctx context.Context, in *ListNotificationHistoryRequest, opts ...grpc.CallOption) (*ListNotificationHistoryReply, error)
	RetryNotification(ctx context.Context, in *RetryNotificationRequest, opts ...grpc.CallOption) (*RetryNotificationReply, error)
	// 事件总线相关接口
	PushExternalAlert(ctx context.Context, in *PushExternalAlertRequest, opts ...grpc.CallOption) (*PushExternalAlertReply, error)
	PushInternalAlert(ctx context.Context, in *PushInternalAlertRequest, opts ...grpc.CallOption) (*PushInternalAlertReply, error)
	// 定时任务相关接口
	ListScheduledTasks(ctx context.Context, in *ListScheduledTasksRequest, opts ...grpc.CallOption) (*ListScheduledTasksReply, error)
	GetScheduledTask(ctx context.Context, in *GetScheduledTaskRequest, opts ...grpc.CallOption) (*ScheduledTaskItem, error)
	UpdateScheduledTaskStatus(ctx context.Context, in *UpdateScheduledTaskStatusRequest, opts ...grpc.CallOption) (*UpdateScheduledTaskStatusReply, error)
}

type eventCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewEventCenterClient(cc grpc.ClientConnInterface) EventCenterClient {
	return &eventCenterClient{cc}
}

func (c *eventCenterClient) ListRealtimeAlerts(ctx context.Context, in *ListRealtimeAlertsRequest, opts ...grpc.CallOption) (*ListRealtimeAlertsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRealtimeAlertsReply)
	err := c.cc.Invoke(ctx, EventCenter_ListRealtimeAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) GetRealtimeAlert(ctx context.Context, in *GetRealtimeAlertRequest, opts ...grpc.CallOption) (*RealtimeAlertItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealtimeAlertItem)
	err := c.cc.Invoke(ctx, EventCenter_GetRealtimeAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) InterveneAlert(ctx context.Context, in *InterveneAlertRequest, opts ...grpc.CallOption) (*InterveneAlertReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterveneAlertReply)
	err := c.cc.Invoke(ctx, EventCenter_InterveneAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) SuppressAlert(ctx context.Context, in *SuppressAlertRequest, opts ...grpc.CallOption) (*SuppressAlertReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuppressAlertReply)
	err := c.cc.Invoke(ctx, EventCenter_SuppressAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) UpgradeAlert(ctx context.Context, in *UpgradeAlertRequest, opts ...grpc.CallOption) (*UpgradeAlertReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeAlertReply)
	err := c.cc.Invoke(ctx, EventCenter_UpgradeAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) GetAlertEventChart(ctx context.Context, in *GetAlertEventChartRequest, opts ...grpc.CallOption) (*GetAlertEventChartReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertEventChartReply)
	err := c.cc.Invoke(ctx, EventCenter_GetAlertEventChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) ListAlertHistory(ctx context.Context, in *ListAlertHistoryRequest, opts ...grpc.CallOption) (*ListAlertHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertHistoryReply)
	err := c.cc.Invoke(ctx, EventCenter_ListAlertHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) GetAlertHistory(ctx context.Context, in *GetAlertHistoryRequest, opts ...grpc.CallOption) (*AlertHistoryItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertHistoryItem)
	err := c.cc.Invoke(ctx, EventCenter_GetAlertHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) GetAlertRawData(ctx context.Context, in *GetAlertRawDataRequest, opts ...grpc.CallOption) (*GetAlertRawDataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertRawDataReply)
	err := c.cc.Invoke(ctx, EventCenter_GetAlertRawData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) GetAlertEventReport(ctx context.Context, in *GetAlertEventReportRequest, opts ...grpc.CallOption) (*GetAlertEventReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertEventReportReply)
	err := c.cc.Invoke(ctx, EventCenter_GetAlertEventReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) ListNotificationHistory(ctx context.Context, in *ListNotificationHistoryRequest, opts ...grpc.CallOption) (*ListNotificationHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotificationHistoryReply)
	err := c.cc.Invoke(ctx, EventCenter_ListNotificationHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) RetryNotification(ctx context.Context, in *RetryNotificationRequest, opts ...grpc.CallOption) (*RetryNotificationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryNotificationReply)
	err := c.cc.Invoke(ctx, EventCenter_RetryNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) PushExternalAlert(ctx context.Context, in *PushExternalAlertRequest, opts ...grpc.CallOption) (*PushExternalAlertReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushExternalAlertReply)
	err := c.cc.Invoke(ctx, EventCenter_PushExternalAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) PushInternalAlert(ctx context.Context, in *PushInternalAlertRequest, opts ...grpc.CallOption) (*PushInternalAlertReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushInternalAlertReply)
	err := c.cc.Invoke(ctx, EventCenter_PushInternalAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) ListScheduledTasks(ctx context.Context, in *ListScheduledTasksRequest, opts ...grpc.CallOption) (*ListScheduledTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScheduledTasksReply)
	err := c.cc.Invoke(ctx, EventCenter_ListScheduledTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) GetScheduledTask(ctx context.Context, in *GetScheduledTaskRequest, opts ...grpc.CallOption) (*ScheduledTaskItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledTaskItem)
	err := c.cc.Invoke(ctx, EventCenter_GetScheduledTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCenterClient) UpdateScheduledTaskStatus(ctx context.Context, in *UpdateScheduledTaskStatusRequest, opts ...grpc.CallOption) (*UpdateScheduledTaskStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateScheduledTaskStatusReply)
	err := c.cc.Invoke(ctx, EventCenter_UpdateScheduledTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventCenterServer is the server API for EventCenter service.
// All implementations must embed UnimplementedEventCenterServer
// for forward compatibility.
//
// 事件中心服务
type EventCenterServer interface {
	// 实时告警相关接口
	ListRealtimeAlerts(context.Context, *ListRealtimeAlertsRequest) (*ListRealtimeAlertsReply, error)
	GetRealtimeAlert(context.Context, *GetRealtimeAlertRequest) (*RealtimeAlertItem, error)
	InterveneAlert(context.Context, *InterveneAlertRequest) (*InterveneAlertReply, error)
	SuppressAlert(context.Context, *SuppressAlertRequest) (*SuppressAlertReply, error)
	UpgradeAlert(context.Context, *UpgradeAlertRequest) (*UpgradeAlertReply, error)
	GetAlertEventChart(context.Context, *GetAlertEventChartRequest) (*GetAlertEventChartReply, error)
	// 告警历史相关接口
	ListAlertHistory(context.Context, *ListAlertHistoryRequest) (*ListAlertHistoryReply, error)
	GetAlertHistory(context.Context, *GetAlertHistoryRequest) (*AlertHistoryItem, error)
	GetAlertRawData(context.Context, *GetAlertRawDataRequest) (*GetAlertRawDataReply, error)
	GetAlertEventReport(context.Context, *GetAlertEventReportRequest) (*GetAlertEventReportReply, error)
	// 通知历史相关接口
	ListNotificationHistory(context.Context, *ListNotificationHistoryRequest) (*ListNotificationHistoryReply, error)
	RetryNotification(context.Context, *RetryNotificationRequest) (*RetryNotificationReply, error)
	// 事件总线相关接口
	PushExternalAlert(context.Context, *PushExternalAlertRequest) (*PushExternalAlertReply, error)
	PushInternalAlert(context.Context, *PushInternalAlertRequest) (*PushInternalAlertReply, error)
	// 定时任务相关接口
	ListScheduledTasks(context.Context, *ListScheduledTasksRequest) (*ListScheduledTasksReply, error)
	GetScheduledTask(context.Context, *GetScheduledTaskRequest) (*ScheduledTaskItem, error)
	UpdateScheduledTaskStatus(context.Context, *UpdateScheduledTaskStatusRequest) (*UpdateScheduledTaskStatusReply, error)
	mustEmbedUnimplementedEventCenterServer()
}

// UnimplementedEventCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventCenterServer struct{}

func (UnimplementedEventCenterServer) ListRealtimeAlerts(context.Context, *ListRealtimeAlertsRequest) (*ListRealtimeAlertsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRealtimeAlerts not implemented")
}
func (UnimplementedEventCenterServer) GetRealtimeAlert(context.Context, *GetRealtimeAlertRequest) (*RealtimeAlertItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealtimeAlert not implemented")
}
func (UnimplementedEventCenterServer) InterveneAlert(context.Context, *InterveneAlertRequest) (*InterveneAlertReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterveneAlert not implemented")
}
func (UnimplementedEventCenterServer) SuppressAlert(context.Context, *SuppressAlertRequest) (*SuppressAlertReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuppressAlert not implemented")
}
func (UnimplementedEventCenterServer) UpgradeAlert(context.Context, *UpgradeAlertRequest) (*UpgradeAlertReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeAlert not implemented")
}
func (UnimplementedEventCenterServer) GetAlertEventChart(context.Context, *GetAlertEventChartRequest) (*GetAlertEventChartReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertEventChart not implemented")
}
func (UnimplementedEventCenterServer) ListAlertHistory(context.Context, *ListAlertHistoryRequest) (*ListAlertHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlertHistory not implemented")
}
func (UnimplementedEventCenterServer) GetAlertHistory(context.Context, *GetAlertHistoryRequest) (*AlertHistoryItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertHistory not implemented")
}
func (UnimplementedEventCenterServer) GetAlertRawData(context.Context, *GetAlertRawDataRequest) (*GetAlertRawDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertRawData not implemented")
}
func (UnimplementedEventCenterServer) GetAlertEventReport(context.Context, *GetAlertEventReportRequest) (*GetAlertEventReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertEventReport not implemented")
}
func (UnimplementedEventCenterServer) ListNotificationHistory(context.Context, *ListNotificationHistoryRequest) (*ListNotificationHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotificationHistory not implemented")
}
func (UnimplementedEventCenterServer) RetryNotification(context.Context, *RetryNotificationRequest) (*RetryNotificationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryNotification not implemented")
}
func (UnimplementedEventCenterServer) PushExternalAlert(context.Context, *PushExternalAlertRequest) (*PushExternalAlertReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushExternalAlert not implemented")
}
func (UnimplementedEventCenterServer) PushInternalAlert(context.Context, *PushInternalAlertRequest) (*PushInternalAlertReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushInternalAlert not implemented")
}
func (UnimplementedEventCenterServer) ListScheduledTasks(context.Context, *ListScheduledTasksRequest) (*ListScheduledTasksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScheduledTasks not implemented")
}
func (UnimplementedEventCenterServer) GetScheduledTask(context.Context, *GetScheduledTaskRequest) (*ScheduledTaskItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduledTask not implemented")
}
func (UnimplementedEventCenterServer) UpdateScheduledTaskStatus(context.Context, *UpdateScheduledTaskStatusRequest) (*UpdateScheduledTaskStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScheduledTaskStatus not implemented")
}
func (UnimplementedEventCenterServer) mustEmbedUnimplementedEventCenterServer() {}
func (UnimplementedEventCenterServer) testEmbeddedByValue()                     {}

// UnsafeEventCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventCenterServer will
// result in compilation errors.
type UnsafeEventCenterServer interface {
	mustEmbedUnimplementedEventCenterServer()
}

func RegisterEventCenterServer(s grpc.ServiceRegistrar, srv EventCenterServer) {
	// If the following call pancis, it indicates UnimplementedEventCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventCenter_ServiceDesc, srv)
}

func _EventCenter_ListRealtimeAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRealtimeAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).ListRealtimeAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_ListRealtimeAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).ListRealtimeAlerts(ctx, req.(*ListRealtimeAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_GetRealtimeAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRealtimeAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).GetRealtimeAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_GetRealtimeAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).GetRealtimeAlert(ctx, req.(*GetRealtimeAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_InterveneAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterveneAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).InterveneAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_InterveneAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).InterveneAlert(ctx, req.(*InterveneAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_SuppressAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuppressAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).SuppressAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_SuppressAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).SuppressAlert(ctx, req.(*SuppressAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_UpgradeAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).UpgradeAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_UpgradeAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).UpgradeAlert(ctx, req.(*UpgradeAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_GetAlertEventChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertEventChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).GetAlertEventChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_GetAlertEventChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).GetAlertEventChart(ctx, req.(*GetAlertEventChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_ListAlertHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).ListAlertHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_ListAlertHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).ListAlertHistory(ctx, req.(*ListAlertHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_GetAlertHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).GetAlertHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_GetAlertHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).GetAlertHistory(ctx, req.(*GetAlertHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_GetAlertRawData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRawDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).GetAlertRawData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_GetAlertRawData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).GetAlertRawData(ctx, req.(*GetAlertRawDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_GetAlertEventReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertEventReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).GetAlertEventReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_GetAlertEventReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).GetAlertEventReport(ctx, req.(*GetAlertEventReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_ListNotificationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).ListNotificationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_ListNotificationHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).ListNotificationHistory(ctx, req.(*ListNotificationHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_RetryNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).RetryNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_RetryNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).RetryNotification(ctx, req.(*RetryNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_PushExternalAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushExternalAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).PushExternalAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_PushExternalAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).PushExternalAlert(ctx, req.(*PushExternalAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_PushInternalAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushInternalAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).PushInternalAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_PushInternalAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).PushInternalAlert(ctx, req.(*PushInternalAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_ListScheduledTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScheduledTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).ListScheduledTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_ListScheduledTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).ListScheduledTasks(ctx, req.(*ListScheduledTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_GetScheduledTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduledTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).GetScheduledTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_GetScheduledTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).GetScheduledTask(ctx, req.(*GetScheduledTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCenter_UpdateScheduledTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScheduledTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCenterServer).UpdateScheduledTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCenter_UpdateScheduledTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCenterServer).UpdateScheduledTaskStatus(ctx, req.(*UpdateScheduledTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventCenter_ServiceDesc is the grpc.ServiceDesc for EventCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereign.api.v1.EventCenter",
	HandlerType: (*EventCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRealtimeAlerts",
			Handler:    _EventCenter_ListRealtimeAlerts_Handler,
		},
		{
			MethodName: "GetRealtimeAlert",
			Handler:    _EventCenter_GetRealtimeAlert_Handler,
		},
		{
			MethodName: "InterveneAlert",
			Handler:    _EventCenter_InterveneAlert_Handler,
		},
		{
			MethodName: "SuppressAlert",
			Handler:    _EventCenter_SuppressAlert_Handler,
		},
		{
			MethodName: "UpgradeAlert",
			Handler:    _EventCenter_UpgradeAlert_Handler,
		},
		{
			MethodName: "GetAlertEventChart",
			Handler:    _EventCenter_GetAlertEventChart_Handler,
		},
		{
			MethodName: "ListAlertHistory",
			Handler:    _EventCenter_ListAlertHistory_Handler,
		},
		{
			MethodName: "GetAlertHistory",
			Handler:    _EventCenter_GetAlertHistory_Handler,
		},
		{
			MethodName: "GetAlertRawData",
			Handler:    _EventCenter_GetAlertRawData_Handler,
		},
		{
			MethodName: "GetAlertEventReport",
			Handler:    _EventCenter_GetAlertEventReport_Handler,
		},
		{
			MethodName: "ListNotificationHistory",
			Handler:    _EventCenter_ListNotificationHistory_Handler,
		},
		{
			MethodName: "RetryNotification",
			Handler:    _EventCenter_RetryNotification_Handler,
		},
		{
			MethodName: "PushExternalAlert",
			Handler:    _EventCenter_PushExternalAlert_Handler,
		},
		{
			MethodName: "PushInternalAlert",
			Handler:    _EventCenter_PushInternalAlert_Handler,
		},
		{
			MethodName: "ListScheduledTasks",
			Handler:    _EventCenter_ListScheduledTasks_Handler,
		},
		{
			MethodName: "GetScheduledTask",
			Handler:    _EventCenter_GetScheduledTask_Handler,
		},
		{
			MethodName: "UpdateScheduledTaskStatus",
			Handler:    _EventCenter_UpdateScheduledTaskStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/event.proto",
}
