// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/v1/strategy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Strategy_CreateStrategy_FullMethodName                   = "/sovereign.api.v1.Strategy/CreateStrategy"
	Strategy_UpdateStrategy_FullMethodName                   = "/sovereign.api.v1.Strategy/UpdateStrategy"
	Strategy_UpdateStrategyStatus_FullMethodName             = "/sovereign.api.v1.Strategy/UpdateStrategyStatus"
	Strategy_DeleteStrategy_FullMethodName                   = "/sovereign.api.v1.Strategy/DeleteStrategy"
	Strategy_GetStrategy_FullMethodName                      = "/sovereign.api.v1.Strategy/GetStrategy"
	Strategy_ListStrategy_FullMethodName                     = "/sovereign.api.v1.Strategy/ListStrategy"
	Strategy_SelectStrategy_FullMethodName                   = "/sovereign.api.v1.Strategy/SelectStrategy"
	Strategy_CreateStrategyGroup_FullMethodName              = "/sovereign.api.v1.Strategy/CreateStrategyGroup"
	Strategy_UpdateStrategyGroup_FullMethodName              = "/sovereign.api.v1.Strategy/UpdateStrategyGroup"
	Strategy_UpdateStrategyGroupStatus_FullMethodName        = "/sovereign.api.v1.Strategy/UpdateStrategyGroupStatus"
	Strategy_DeleteStrategyGroup_FullMethodName              = "/sovereign.api.v1.Strategy/DeleteStrategyGroup"
	Strategy_GetStrategyGroup_FullMethodName                 = "/sovereign.api.v1.Strategy/GetStrategyGroup"
	Strategy_ListStrategyGroup_FullMethodName                = "/sovereign.api.v1.Strategy/ListStrategyGroup"
	Strategy_GetGroupStrategies_FullMethodName               = "/sovereign.api.v1.Strategy/GetGroupStrategies"
	Strategy_AddStrategyToGroup_FullMethodName               = "/sovereign.api.v1.Strategy/AddStrategyToGroup"
	Strategy_RemoveStrategyFromGroup_FullMethodName          = "/sovereign.api.v1.Strategy/RemoveStrategyFromGroup"
	Strategy_UpdateStrategyGroupUpgradeMode_FullMethodName   = "/sovereign.api.v1.Strategy/UpdateStrategyGroupUpgradeMode"
	Strategy_UpdateStrategyGroupUpgradeConfig_FullMethodName = "/sovereign.api.v1.Strategy/UpdateStrategyGroupUpgradeConfig"
	Strategy_CreateReceiver_FullMethodName                   = "/sovereign.api.v1.Strategy/CreateReceiver"
	Strategy_UpdateReceiver_FullMethodName                   = "/sovereign.api.v1.Strategy/UpdateReceiver"
	Strategy_DeleteReceiver_FullMethodName                   = "/sovereign.api.v1.Strategy/DeleteReceiver"
	Strategy_GetReceiver_FullMethodName                      = "/sovereign.api.v1.Strategy/GetReceiver"
	Strategy_ListReceiver_FullMethodName                     = "/sovereign.api.v1.Strategy/ListReceiver"
	Strategy_CreateStrategyRule_FullMethodName               = "/sovereign.api.v1.Strategy/CreateStrategyRule"
	Strategy_UpdateStrategyRule_FullMethodName               = "/sovereign.api.v1.Strategy/UpdateStrategyRule"
	Strategy_DeleteStrategyRule_FullMethodName               = "/sovereign.api.v1.Strategy/DeleteStrategyRule"
	Strategy_GetStrategyRule_FullMethodName                  = "/sovereign.api.v1.Strategy/GetStrategyRule"
	Strategy_ListStrategyRule_FullMethodName                 = "/sovereign.api.v1.Strategy/ListStrategyRule"
	Strategy_UpdateStrategyRuleStatus_FullMethodName         = "/sovereign.api.v1.Strategy/UpdateStrategyRuleStatus"
	Strategy_UpdateStrategyDataSourceConfig_FullMethodName   = "/sovereign.api.v1.Strategy/UpdateStrategyDataSourceConfig"
	Strategy_UpdateStrategyAlertConfig_FullMethodName        = "/sovereign.api.v1.Strategy/UpdateStrategyAlertConfig"
	Strategy_UpdateStrategyNotifyConfig_FullMethodName       = "/sovereign.api.v1.Strategy/UpdateStrategyNotifyConfig"
	Strategy_UpdateStrategyDialTestConfig_FullMethodName     = "/sovereign.api.v1.Strategy/UpdateStrategyDialTestConfig"
	Strategy_UpdateStrategySuppressConfig_FullMethodName     = "/sovereign.api.v1.Strategy/UpdateStrategySuppressConfig"
)

// StrategyClient is the client API for Strategy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyClient interface {
	CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*CreateStrategyReply, error)
	UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*UpdateStrategyReply, error)
	UpdateStrategyStatus(ctx context.Context, in *UpdateStrategyStatusRequest, opts ...grpc.CallOption) (*UpdateStrategyStatusReply, error)
	DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyReply, error)
	GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*StrategyItem, error)
	ListStrategy(ctx context.Context, in *ListStrategyRequest, opts ...grpc.CallOption) (*ListStrategyReply, error)
	SelectStrategy(ctx context.Context, in *SelectStrategyRequest, opts ...grpc.CallOption) (*SelectStrategyReply, error)
	// 策略分组相关接口
	CreateStrategyGroup(ctx context.Context, in *CreateStrategyGroupRequest, opts ...grpc.CallOption) (*CreateStrategyGroupReply, error)
	UpdateStrategyGroup(ctx context.Context, in *UpdateStrategyGroupRequest, opts ...grpc.CallOption) (*UpdateStrategyGroupReply, error)
	UpdateStrategyGroupStatus(ctx context.Context, in *UpdateStrategyGroupStatusRequest, opts ...grpc.CallOption) (*UpdateStrategyGroupStatusReply, error)
	DeleteStrategyGroup(ctx context.Context, in *DeleteStrategyGroupRequest, opts ...grpc.CallOption) (*DeleteStrategyGroupReply, error)
	GetStrategyGroup(ctx context.Context, in *GetStrategyGroupRequest, opts ...grpc.CallOption) (*StrategyGroupItem, error)
	ListStrategyGroup(ctx context.Context, in *ListStrategyGroupRequest, opts ...grpc.CallOption) (*ListStrategyGroupReply, error)
	GetGroupStrategies(ctx context.Context, in *GetGroupStrategiesRequest, opts ...grpc.CallOption) (*ListStrategyReply, error)
	AddStrategyToGroup(ctx context.Context, in *AddStrategyToGroupRequest, opts ...grpc.CallOption) (*AddStrategyToGroupReply, error)
	RemoveStrategyFromGroup(ctx context.Context, in *RemoveStrategyFromGroupRequest, opts ...grpc.CallOption) (*RemoveStrategyFromGroupReply, error)
	// 策略组升级模式更新接口
	UpdateStrategyGroupUpgradeMode(ctx context.Context, in *UpdateStrategyGroupUpgradeModeRequest, opts ...grpc.CallOption) (*UpdateStrategyGroupUpgradeModeReply, error)
	UpdateStrategyGroupUpgradeConfig(ctx context.Context, in *UpdateStrategyGroupUpgradeConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyGroupUpgradeConfigReply, error)
	// 接收对象相关接口
	CreateReceiver(ctx context.Context, in *CreateReceiverRequest, opts ...grpc.CallOption) (*CreateReceiverReply, error)
	UpdateReceiver(ctx context.Context, in *UpdateReceiverRequest, opts ...grpc.CallOption) (*UpdateReceiverReply, error)
	DeleteReceiver(ctx context.Context, in *DeleteReceiverRequest, opts ...grpc.CallOption) (*DeleteReceiverReply, error)
	GetReceiver(ctx context.Context, in *GetReceiverRequest, opts ...grpc.CallOption) (*ReceiverItem, error)
	ListReceiver(ctx context.Context, in *ListReceiverRequest, opts ...grpc.CallOption) (*ListReceiverReply, error)
	// 策略规则相关接口
	CreateStrategyRule(ctx context.Context, in *CreateStrategyRuleRequest, opts ...grpc.CallOption) (*CreateStrategyRuleReply, error)
	UpdateStrategyRule(ctx context.Context, in *UpdateStrategyRuleRequest, opts ...grpc.CallOption) (*UpdateStrategyRuleReply, error)
	DeleteStrategyRule(ctx context.Context, in *DeleteStrategyRuleRequest, opts ...grpc.CallOption) (*DeleteStrategyRuleReply, error)
	GetStrategyRule(ctx context.Context, in *GetStrategyRuleRequest, opts ...grpc.CallOption) (*StrategyRuleItem, error)
	ListStrategyRule(ctx context.Context, in *ListStrategyRuleRequest, opts ...grpc.CallOption) (*ListStrategyRuleReply, error)
	UpdateStrategyRuleStatus(ctx context.Context, in *UpdateStrategyRuleStatusRequest, opts ...grpc.CallOption) (*UpdateStrategyRuleStatusReply, error)
	// 策略详细配置更新接口
	UpdateStrategyDataSourceConfig(ctx context.Context, in *UpdateStrategyDataSourceConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyDataSourceConfigReply, error)
	UpdateStrategyAlertConfig(ctx context.Context, in *UpdateStrategyAlertConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyAlertConfigReply, error)
	UpdateStrategyNotifyConfig(ctx context.Context, in *UpdateStrategyNotifyConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyNotifyConfigReply, error)
	UpdateStrategyDialTestConfig(ctx context.Context, in *UpdateStrategyDialTestConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyDialTestConfigReply, error)
	UpdateStrategySuppressConfig(ctx context.Context, in *UpdateStrategySuppressConfigRequest, opts ...grpc.CallOption) (*UpdateStrategySuppressConfigReply, error)
}

type strategyClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyClient(cc grpc.ClientConnInterface) StrategyClient {
	return &strategyClient{cc}
}

func (c *strategyClient) CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*CreateStrategyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStrategyReply)
	err := c.cc.Invoke(ctx, Strategy_CreateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*UpdateStrategyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyStatus(ctx context.Context, in *UpdateStrategyStatusRequest, opts ...grpc.CallOption) (*UpdateStrategyStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyStatusReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStrategyReply)
	err := c.cc.Invoke(ctx, Strategy_DeleteStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*StrategyItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyItem)
	err := c.cc.Invoke(ctx, Strategy_GetStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) ListStrategy(ctx context.Context, in *ListStrategyRequest, opts ...grpc.CallOption) (*ListStrategyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStrategyReply)
	err := c.cc.Invoke(ctx, Strategy_ListStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) SelectStrategy(ctx context.Context, in *SelectStrategyRequest, opts ...grpc.CallOption) (*SelectStrategyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectStrategyReply)
	err := c.cc.Invoke(ctx, Strategy_SelectStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) CreateStrategyGroup(ctx context.Context, in *CreateStrategyGroupRequest, opts ...grpc.CallOption) (*CreateStrategyGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStrategyGroupReply)
	err := c.cc.Invoke(ctx, Strategy_CreateStrategyGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyGroup(ctx context.Context, in *UpdateStrategyGroupRequest, opts ...grpc.CallOption) (*UpdateStrategyGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyGroupReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyGroupStatus(ctx context.Context, in *UpdateStrategyGroupStatusRequest, opts ...grpc.CallOption) (*UpdateStrategyGroupStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyGroupStatusReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyGroupStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) DeleteStrategyGroup(ctx context.Context, in *DeleteStrategyGroupRequest, opts ...grpc.CallOption) (*DeleteStrategyGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStrategyGroupReply)
	err := c.cc.Invoke(ctx, Strategy_DeleteStrategyGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) GetStrategyGroup(ctx context.Context, in *GetStrategyGroupRequest, opts ...grpc.CallOption) (*StrategyGroupItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyGroupItem)
	err := c.cc.Invoke(ctx, Strategy_GetStrategyGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) ListStrategyGroup(ctx context.Context, in *ListStrategyGroupRequest, opts ...grpc.CallOption) (*ListStrategyGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStrategyGroupReply)
	err := c.cc.Invoke(ctx, Strategy_ListStrategyGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) GetGroupStrategies(ctx context.Context, in *GetGroupStrategiesRequest, opts ...grpc.CallOption) (*ListStrategyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStrategyReply)
	err := c.cc.Invoke(ctx, Strategy_GetGroupStrategies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) AddStrategyToGroup(ctx context.Context, in *AddStrategyToGroupRequest, opts ...grpc.CallOption) (*AddStrategyToGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddStrategyToGroupReply)
	err := c.cc.Invoke(ctx, Strategy_AddStrategyToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) RemoveStrategyFromGroup(ctx context.Context, in *RemoveStrategyFromGroupRequest, opts ...grpc.CallOption) (*RemoveStrategyFromGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveStrategyFromGroupReply)
	err := c.cc.Invoke(ctx, Strategy_RemoveStrategyFromGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyGroupUpgradeMode(ctx context.Context, in *UpdateStrategyGroupUpgradeModeRequest, opts ...grpc.CallOption) (*UpdateStrategyGroupUpgradeModeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyGroupUpgradeModeReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyGroupUpgradeMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyGroupUpgradeConfig(ctx context.Context, in *UpdateStrategyGroupUpgradeConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyGroupUpgradeConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyGroupUpgradeConfigReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyGroupUpgradeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) CreateReceiver(ctx context.Context, in *CreateReceiverRequest, opts ...grpc.CallOption) (*CreateReceiverReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReceiverReply)
	err := c.cc.Invoke(ctx, Strategy_CreateReceiver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateReceiver(ctx context.Context, in *UpdateReceiverRequest, opts ...grpc.CallOption) (*UpdateReceiverReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReceiverReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateReceiver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) DeleteReceiver(ctx context.Context, in *DeleteReceiverRequest, opts ...grpc.CallOption) (*DeleteReceiverReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReceiverReply)
	err := c.cc.Invoke(ctx, Strategy_DeleteReceiver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) GetReceiver(ctx context.Context, in *GetReceiverRequest, opts ...grpc.CallOption) (*ReceiverItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiverItem)
	err := c.cc.Invoke(ctx, Strategy_GetReceiver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) ListReceiver(ctx context.Context, in *ListReceiverRequest, opts ...grpc.CallOption) (*ListReceiverReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReceiverReply)
	err := c.cc.Invoke(ctx, Strategy_ListReceiver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) CreateStrategyRule(ctx context.Context, in *CreateStrategyRuleRequest, opts ...grpc.CallOption) (*CreateStrategyRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStrategyRuleReply)
	err := c.cc.Invoke(ctx, Strategy_CreateStrategyRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyRule(ctx context.Context, in *UpdateStrategyRuleRequest, opts ...grpc.CallOption) (*UpdateStrategyRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyRuleReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) DeleteStrategyRule(ctx context.Context, in *DeleteStrategyRuleRequest, opts ...grpc.CallOption) (*DeleteStrategyRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStrategyRuleReply)
	err := c.cc.Invoke(ctx, Strategy_DeleteStrategyRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) GetStrategyRule(ctx context.Context, in *GetStrategyRuleRequest, opts ...grpc.CallOption) (*StrategyRuleItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyRuleItem)
	err := c.cc.Invoke(ctx, Strategy_GetStrategyRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) ListStrategyRule(ctx context.Context, in *ListStrategyRuleRequest, opts ...grpc.CallOption) (*ListStrategyRuleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStrategyRuleReply)
	err := c.cc.Invoke(ctx, Strategy_ListStrategyRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyRuleStatus(ctx context.Context, in *UpdateStrategyRuleStatusRequest, opts ...grpc.CallOption) (*UpdateStrategyRuleStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyRuleStatusReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyRuleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyDataSourceConfig(ctx context.Context, in *UpdateStrategyDataSourceConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyDataSourceConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyDataSourceConfigReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyDataSourceConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyAlertConfig(ctx context.Context, in *UpdateStrategyAlertConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyAlertConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyAlertConfigReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyAlertConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyNotifyConfig(ctx context.Context, in *UpdateStrategyNotifyConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyNotifyConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyNotifyConfigReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyNotifyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategyDialTestConfig(ctx context.Context, in *UpdateStrategyDialTestConfigRequest, opts ...grpc.CallOption) (*UpdateStrategyDialTestConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyDialTestConfigReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategyDialTestConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) UpdateStrategySuppressConfig(ctx context.Context, in *UpdateStrategySuppressConfigRequest, opts ...grpc.CallOption) (*UpdateStrategySuppressConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategySuppressConfigReply)
	err := c.cc.Invoke(ctx, Strategy_UpdateStrategySuppressConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyServer is the server API for Strategy service.
// All implementations must embed UnimplementedStrategyServer
// for forward compatibility.
type StrategyServer interface {
	CreateStrategy(context.Context, *CreateStrategyRequest) (*CreateStrategyReply, error)
	UpdateStrategy(context.Context, *UpdateStrategyRequest) (*UpdateStrategyReply, error)
	UpdateStrategyStatus(context.Context, *UpdateStrategyStatusRequest) (*UpdateStrategyStatusReply, error)
	DeleteStrategy(context.Context, *DeleteStrategyRequest) (*DeleteStrategyReply, error)
	GetStrategy(context.Context, *GetStrategyRequest) (*StrategyItem, error)
	ListStrategy(context.Context, *ListStrategyRequest) (*ListStrategyReply, error)
	SelectStrategy(context.Context, *SelectStrategyRequest) (*SelectStrategyReply, error)
	// 策略分组相关接口
	CreateStrategyGroup(context.Context, *CreateStrategyGroupRequest) (*CreateStrategyGroupReply, error)
	UpdateStrategyGroup(context.Context, *UpdateStrategyGroupRequest) (*UpdateStrategyGroupReply, error)
	UpdateStrategyGroupStatus(context.Context, *UpdateStrategyGroupStatusRequest) (*UpdateStrategyGroupStatusReply, error)
	DeleteStrategyGroup(context.Context, *DeleteStrategyGroupRequest) (*DeleteStrategyGroupReply, error)
	GetStrategyGroup(context.Context, *GetStrategyGroupRequest) (*StrategyGroupItem, error)
	ListStrategyGroup(context.Context, *ListStrategyGroupRequest) (*ListStrategyGroupReply, error)
	GetGroupStrategies(context.Context, *GetGroupStrategiesRequest) (*ListStrategyReply, error)
	AddStrategyToGroup(context.Context, *AddStrategyToGroupRequest) (*AddStrategyToGroupReply, error)
	RemoveStrategyFromGroup(context.Context, *RemoveStrategyFromGroupRequest) (*RemoveStrategyFromGroupReply, error)
	// 策略组升级模式更新接口
	UpdateStrategyGroupUpgradeMode(context.Context, *UpdateStrategyGroupUpgradeModeRequest) (*UpdateStrategyGroupUpgradeModeReply, error)
	UpdateStrategyGroupUpgradeConfig(context.Context, *UpdateStrategyGroupUpgradeConfigRequest) (*UpdateStrategyGroupUpgradeConfigReply, error)
	// 接收对象相关接口
	CreateReceiver(context.Context, *CreateReceiverRequest) (*CreateReceiverReply, error)
	UpdateReceiver(context.Context, *UpdateReceiverRequest) (*UpdateReceiverReply, error)
	DeleteReceiver(context.Context, *DeleteReceiverRequest) (*DeleteReceiverReply, error)
	GetReceiver(context.Context, *GetReceiverRequest) (*ReceiverItem, error)
	ListReceiver(context.Context, *ListReceiverRequest) (*ListReceiverReply, error)
	// 策略规则相关接口
	CreateStrategyRule(context.Context, *CreateStrategyRuleRequest) (*CreateStrategyRuleReply, error)
	UpdateStrategyRule(context.Context, *UpdateStrategyRuleRequest) (*UpdateStrategyRuleReply, error)
	DeleteStrategyRule(context.Context, *DeleteStrategyRuleRequest) (*DeleteStrategyRuleReply, error)
	GetStrategyRule(context.Context, *GetStrategyRuleRequest) (*StrategyRuleItem, error)
	ListStrategyRule(context.Context, *ListStrategyRuleRequest) (*ListStrategyRuleReply, error)
	UpdateStrategyRuleStatus(context.Context, *UpdateStrategyRuleStatusRequest) (*UpdateStrategyRuleStatusReply, error)
	// 策略详细配置更新接口
	UpdateStrategyDataSourceConfig(context.Context, *UpdateStrategyDataSourceConfigRequest) (*UpdateStrategyDataSourceConfigReply, error)
	UpdateStrategyAlertConfig(context.Context, *UpdateStrategyAlertConfigRequest) (*UpdateStrategyAlertConfigReply, error)
	UpdateStrategyNotifyConfig(context.Context, *UpdateStrategyNotifyConfigRequest) (*UpdateStrategyNotifyConfigReply, error)
	UpdateStrategyDialTestConfig(context.Context, *UpdateStrategyDialTestConfigRequest) (*UpdateStrategyDialTestConfigReply, error)
	UpdateStrategySuppressConfig(context.Context, *UpdateStrategySuppressConfigRequest) (*UpdateStrategySuppressConfigReply, error)
	mustEmbedUnimplementedStrategyServer()
}

// UnimplementedStrategyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyServer struct{}

func (UnimplementedStrategyServer) CreateStrategy(context.Context, *CreateStrategyRequest) (*CreateStrategyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStrategy not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategy(context.Context, *UpdateStrategyRequest) (*UpdateStrategyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategy not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyStatus(context.Context, *UpdateStrategyStatusRequest) (*UpdateStrategyStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyStatus not implemented")
}
func (UnimplementedStrategyServer) DeleteStrategy(context.Context, *DeleteStrategyRequest) (*DeleteStrategyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStrategy not implemented")
}
func (UnimplementedStrategyServer) GetStrategy(context.Context, *GetStrategyRequest) (*StrategyItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrategy not implemented")
}
func (UnimplementedStrategyServer) ListStrategy(context.Context, *ListStrategyRequest) (*ListStrategyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStrategy not implemented")
}
func (UnimplementedStrategyServer) SelectStrategy(context.Context, *SelectStrategyRequest) (*SelectStrategyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectStrategy not implemented")
}
func (UnimplementedStrategyServer) CreateStrategyGroup(context.Context, *CreateStrategyGroupRequest) (*CreateStrategyGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStrategyGroup not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyGroup(context.Context, *UpdateStrategyGroupRequest) (*UpdateStrategyGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyGroup not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyGroupStatus(context.Context, *UpdateStrategyGroupStatusRequest) (*UpdateStrategyGroupStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyGroupStatus not implemented")
}
func (UnimplementedStrategyServer) DeleteStrategyGroup(context.Context, *DeleteStrategyGroupRequest) (*DeleteStrategyGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStrategyGroup not implemented")
}
func (UnimplementedStrategyServer) GetStrategyGroup(context.Context, *GetStrategyGroupRequest) (*StrategyGroupItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrategyGroup not implemented")
}
func (UnimplementedStrategyServer) ListStrategyGroup(context.Context, *ListStrategyGroupRequest) (*ListStrategyGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStrategyGroup not implemented")
}
func (UnimplementedStrategyServer) GetGroupStrategies(context.Context, *GetGroupStrategiesRequest) (*ListStrategyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupStrategies not implemented")
}
func (UnimplementedStrategyServer) AddStrategyToGroup(context.Context, *AddStrategyToGroupRequest) (*AddStrategyToGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStrategyToGroup not implemented")
}
func (UnimplementedStrategyServer) RemoveStrategyFromGroup(context.Context, *RemoveStrategyFromGroupRequest) (*RemoveStrategyFromGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveStrategyFromGroup not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyGroupUpgradeMode(context.Context, *UpdateStrategyGroupUpgradeModeRequest) (*UpdateStrategyGroupUpgradeModeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyGroupUpgradeMode not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyGroupUpgradeConfig(context.Context, *UpdateStrategyGroupUpgradeConfigRequest) (*UpdateStrategyGroupUpgradeConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyGroupUpgradeConfig not implemented")
}
func (UnimplementedStrategyServer) CreateReceiver(context.Context, *CreateReceiverRequest) (*CreateReceiverReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReceiver not implemented")
}
func (UnimplementedStrategyServer) UpdateReceiver(context.Context, *UpdateReceiverRequest) (*UpdateReceiverReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReceiver not implemented")
}
func (UnimplementedStrategyServer) DeleteReceiver(context.Context, *DeleteReceiverRequest) (*DeleteReceiverReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReceiver not implemented")
}
func (UnimplementedStrategyServer) GetReceiver(context.Context, *GetReceiverRequest) (*ReceiverItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReceiver not implemented")
}
func (UnimplementedStrategyServer) ListReceiver(context.Context, *ListReceiverRequest) (*ListReceiverReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReceiver not implemented")
}
func (UnimplementedStrategyServer) CreateStrategyRule(context.Context, *CreateStrategyRuleRequest) (*CreateStrategyRuleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStrategyRule not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyRule(context.Context, *UpdateStrategyRuleRequest) (*UpdateStrategyRuleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyRule not implemented")
}
func (UnimplementedStrategyServer) DeleteStrategyRule(context.Context, *DeleteStrategyRuleRequest) (*DeleteStrategyRuleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStrategyRule not implemented")
}
func (UnimplementedStrategyServer) GetStrategyRule(context.Context, *GetStrategyRuleRequest) (*StrategyRuleItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrategyRule not implemented")
}
func (UnimplementedStrategyServer) ListStrategyRule(context.Context, *ListStrategyRuleRequest) (*ListStrategyRuleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStrategyRule not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyRuleStatus(context.Context, *UpdateStrategyRuleStatusRequest) (*UpdateStrategyRuleStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyRuleStatus not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyDataSourceConfig(context.Context, *UpdateStrategyDataSourceConfigRequest) (*UpdateStrategyDataSourceConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyDataSourceConfig not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyAlertConfig(context.Context, *UpdateStrategyAlertConfigRequest) (*UpdateStrategyAlertConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyAlertConfig not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyNotifyConfig(context.Context, *UpdateStrategyNotifyConfigRequest) (*UpdateStrategyNotifyConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyNotifyConfig not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategyDialTestConfig(context.Context, *UpdateStrategyDialTestConfigRequest) (*UpdateStrategyDialTestConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategyDialTestConfig not implemented")
}
func (UnimplementedStrategyServer) UpdateStrategySuppressConfig(context.Context, *UpdateStrategySuppressConfigRequest) (*UpdateStrategySuppressConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategySuppressConfig not implemented")
}
func (UnimplementedStrategyServer) mustEmbedUnimplementedStrategyServer() {}
func (UnimplementedStrategyServer) testEmbeddedByValue()                  {}

// UnsafeStrategyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyServer will
// result in compilation errors.
type UnsafeStrategyServer interface {
	mustEmbedUnimplementedStrategyServer()
}

func RegisterStrategyServer(s grpc.ServiceRegistrar, srv StrategyServer) {
	// If the following call pancis, it indicates UnimplementedStrategyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Strategy_ServiceDesc, srv)
}

func _Strategy_CreateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).CreateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_CreateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).CreateStrategy(ctx, req.(*CreateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategy(ctx, req.(*UpdateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyStatus(ctx, req.(*UpdateStrategyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_DeleteStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).DeleteStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_DeleteStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).DeleteStrategy(ctx, req.(*DeleteStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_GetStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).GetStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_GetStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).GetStrategy(ctx, req.(*GetStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_ListStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).ListStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_ListStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).ListStrategy(ctx, req.(*ListStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_SelectStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).SelectStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_SelectStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).SelectStrategy(ctx, req.(*SelectStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_CreateStrategyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStrategyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).CreateStrategyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_CreateStrategyGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).CreateStrategyGroup(ctx, req.(*CreateStrategyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyGroup(ctx, req.(*UpdateStrategyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyGroupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyGroupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyGroupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyGroupStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyGroupStatus(ctx, req.(*UpdateStrategyGroupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_DeleteStrategyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStrategyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).DeleteStrategyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_DeleteStrategyGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).DeleteStrategyGroup(ctx, req.(*DeleteStrategyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_GetStrategyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).GetStrategyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_GetStrategyGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).GetStrategyGroup(ctx, req.(*GetStrategyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_ListStrategyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStrategyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).ListStrategyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_ListStrategyGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).ListStrategyGroup(ctx, req.(*ListStrategyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_GetGroupStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupStrategiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).GetGroupStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_GetGroupStrategies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).GetGroupStrategies(ctx, req.(*GetGroupStrategiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_AddStrategyToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStrategyToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).AddStrategyToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_AddStrategyToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).AddStrategyToGroup(ctx, req.(*AddStrategyToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_RemoveStrategyFromGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveStrategyFromGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).RemoveStrategyFromGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_RemoveStrategyFromGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).RemoveStrategyFromGroup(ctx, req.(*RemoveStrategyFromGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyGroupUpgradeMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyGroupUpgradeModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyGroupUpgradeMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyGroupUpgradeMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyGroupUpgradeMode(ctx, req.(*UpdateStrategyGroupUpgradeModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyGroupUpgradeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyGroupUpgradeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyGroupUpgradeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyGroupUpgradeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyGroupUpgradeConfig(ctx, req.(*UpdateStrategyGroupUpgradeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_CreateReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).CreateReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_CreateReceiver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).CreateReceiver(ctx, req.(*CreateReceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateReceiver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateReceiver(ctx, req.(*UpdateReceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_DeleteReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).DeleteReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_DeleteReceiver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).DeleteReceiver(ctx, req.(*DeleteReceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_GetReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).GetReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_GetReceiver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).GetReceiver(ctx, req.(*GetReceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_ListReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).ListReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_ListReceiver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).ListReceiver(ctx, req.(*ListReceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_CreateStrategyRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStrategyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).CreateStrategyRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_CreateStrategyRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).CreateStrategyRule(ctx, req.(*CreateStrategyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyRule(ctx, req.(*UpdateStrategyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_DeleteStrategyRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStrategyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).DeleteStrategyRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_DeleteStrategyRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).DeleteStrategyRule(ctx, req.(*DeleteStrategyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_GetStrategyRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).GetStrategyRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_GetStrategyRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).GetStrategyRule(ctx, req.(*GetStrategyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_ListStrategyRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStrategyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).ListStrategyRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_ListStrategyRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).ListStrategyRule(ctx, req.(*ListStrategyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyRuleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyRuleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyRuleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyRuleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyRuleStatus(ctx, req.(*UpdateStrategyRuleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyDataSourceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyDataSourceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyDataSourceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyDataSourceConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyDataSourceConfig(ctx, req.(*UpdateStrategyDataSourceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyAlertConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyAlertConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyAlertConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyAlertConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyAlertConfig(ctx, req.(*UpdateStrategyAlertConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyNotifyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyNotifyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyNotifyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyNotifyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyNotifyConfig(ctx, req.(*UpdateStrategyNotifyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategyDialTestConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyDialTestConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategyDialTestConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategyDialTestConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategyDialTestConfig(ctx, req.(*UpdateStrategyDialTestConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_UpdateStrategySuppressConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategySuppressConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).UpdateStrategySuppressConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Strategy_UpdateStrategySuppressConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).UpdateStrategySuppressConfig(ctx, req.(*UpdateStrategySuppressConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Strategy_ServiceDesc is the grpc.ServiceDesc for Strategy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Strategy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereign.api.v1.Strategy",
	HandlerType: (*StrategyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStrategy",
			Handler:    _Strategy_CreateStrategy_Handler,
		},
		{
			MethodName: "UpdateStrategy",
			Handler:    _Strategy_UpdateStrategy_Handler,
		},
		{
			MethodName: "UpdateStrategyStatus",
			Handler:    _Strategy_UpdateStrategyStatus_Handler,
		},
		{
			MethodName: "DeleteStrategy",
			Handler:    _Strategy_DeleteStrategy_Handler,
		},
		{
			MethodName: "GetStrategy",
			Handler:    _Strategy_GetStrategy_Handler,
		},
		{
			MethodName: "ListStrategy",
			Handler:    _Strategy_ListStrategy_Handler,
		},
		{
			MethodName: "SelectStrategy",
			Handler:    _Strategy_SelectStrategy_Handler,
		},
		{
			MethodName: "CreateStrategyGroup",
			Handler:    _Strategy_CreateStrategyGroup_Handler,
		},
		{
			MethodName: "UpdateStrategyGroup",
			Handler:    _Strategy_UpdateStrategyGroup_Handler,
		},
		{
			MethodName: "UpdateStrategyGroupStatus",
			Handler:    _Strategy_UpdateStrategyGroupStatus_Handler,
		},
		{
			MethodName: "DeleteStrategyGroup",
			Handler:    _Strategy_DeleteStrategyGroup_Handler,
		},
		{
			MethodName: "GetStrategyGroup",
			Handler:    _Strategy_GetStrategyGroup_Handler,
		},
		{
			MethodName: "ListStrategyGroup",
			Handler:    _Strategy_ListStrategyGroup_Handler,
		},
		{
			MethodName: "GetGroupStrategies",
			Handler:    _Strategy_GetGroupStrategies_Handler,
		},
		{
			MethodName: "AddStrategyToGroup",
			Handler:    _Strategy_AddStrategyToGroup_Handler,
		},
		{
			MethodName: "RemoveStrategyFromGroup",
			Handler:    _Strategy_RemoveStrategyFromGroup_Handler,
		},
		{
			MethodName: "UpdateStrategyGroupUpgradeMode",
			Handler:    _Strategy_UpdateStrategyGroupUpgradeMode_Handler,
		},
		{
			MethodName: "UpdateStrategyGroupUpgradeConfig",
			Handler:    _Strategy_UpdateStrategyGroupUpgradeConfig_Handler,
		},
		{
			MethodName: "CreateReceiver",
			Handler:    _Strategy_CreateReceiver_Handler,
		},
		{
			MethodName: "UpdateReceiver",
			Handler:    _Strategy_UpdateReceiver_Handler,
		},
		{
			MethodName: "DeleteReceiver",
			Handler:    _Strategy_DeleteReceiver_Handler,
		},
		{
			MethodName: "GetReceiver",
			Handler:    _Strategy_GetReceiver_Handler,
		},
		{
			MethodName: "ListReceiver",
			Handler:    _Strategy_ListReceiver_Handler,
		},
		{
			MethodName: "CreateStrategyRule",
			Handler:    _Strategy_CreateStrategyRule_Handler,
		},
		{
			MethodName: "UpdateStrategyRule",
			Handler:    _Strategy_UpdateStrategyRule_Handler,
		},
		{
			MethodName: "DeleteStrategyRule",
			Handler:    _Strategy_DeleteStrategyRule_Handler,
		},
		{
			MethodName: "GetStrategyRule",
			Handler:    _Strategy_GetStrategyRule_Handler,
		},
		{
			MethodName: "ListStrategyRule",
			Handler:    _Strategy_ListStrategyRule_Handler,
		},
		{
			MethodName: "UpdateStrategyRuleStatus",
			Handler:    _Strategy_UpdateStrategyRuleStatus_Handler,
		},
		{
			MethodName: "UpdateStrategyDataSourceConfig",
			Handler:    _Strategy_UpdateStrategyDataSourceConfig_Handler,
		},
		{
			MethodName: "UpdateStrategyAlertConfig",
			Handler:    _Strategy_UpdateStrategyAlertConfig_Handler,
		},
		{
			MethodName: "UpdateStrategyNotifyConfig",
			Handler:    _Strategy_UpdateStrategyNotifyConfig_Handler,
		},
		{
			MethodName: "UpdateStrategyDialTestConfig",
			Handler:    _Strategy_UpdateStrategyDialTestConfig_Handler,
		},
		{
			MethodName: "UpdateStrategySuppressConfig",
			Handler:    _Strategy_UpdateStrategySuppressConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/strategy.proto",
}
