// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.32.1
// source: api/v1/strategy.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStrategyAddStrategyToGroup = "/sovereign.api.v1.Strategy/AddStrategyToGroup"
const OperationStrategyCreateReceiver = "/sovereign.api.v1.Strategy/CreateReceiver"
const OperationStrategyCreateStrategy = "/sovereign.api.v1.Strategy/CreateStrategy"
const OperationStrategyCreateStrategyGroup = "/sovereign.api.v1.Strategy/CreateStrategyGroup"
const OperationStrategyCreateStrategyRule = "/sovereign.api.v1.Strategy/CreateStrategyRule"
const OperationStrategyDeleteReceiver = "/sovereign.api.v1.Strategy/DeleteReceiver"
const OperationStrategyDeleteStrategy = "/sovereign.api.v1.Strategy/DeleteStrategy"
const OperationStrategyDeleteStrategyGroup = "/sovereign.api.v1.Strategy/DeleteStrategyGroup"
const OperationStrategyDeleteStrategyRule = "/sovereign.api.v1.Strategy/DeleteStrategyRule"
const OperationStrategyGetGroupStrategies = "/sovereign.api.v1.Strategy/GetGroupStrategies"
const OperationStrategyGetReceiver = "/sovereign.api.v1.Strategy/GetReceiver"
const OperationStrategyGetStrategy = "/sovereign.api.v1.Strategy/GetStrategy"
const OperationStrategyGetStrategyGroup = "/sovereign.api.v1.Strategy/GetStrategyGroup"
const OperationStrategyGetStrategyRule = "/sovereign.api.v1.Strategy/GetStrategyRule"
const OperationStrategyListReceiver = "/sovereign.api.v1.Strategy/ListReceiver"
const OperationStrategyListStrategy = "/sovereign.api.v1.Strategy/ListStrategy"
const OperationStrategyListStrategyGroup = "/sovereign.api.v1.Strategy/ListStrategyGroup"
const OperationStrategyListStrategyRule = "/sovereign.api.v1.Strategy/ListStrategyRule"
const OperationStrategyRemoveStrategyFromGroup = "/sovereign.api.v1.Strategy/RemoveStrategyFromGroup"
const OperationStrategySelectStrategy = "/sovereign.api.v1.Strategy/SelectStrategy"
const OperationStrategyUpdateReceiver = "/sovereign.api.v1.Strategy/UpdateReceiver"
const OperationStrategyUpdateStrategy = "/sovereign.api.v1.Strategy/UpdateStrategy"
const OperationStrategyUpdateStrategyAlertConfig = "/sovereign.api.v1.Strategy/UpdateStrategyAlertConfig"
const OperationStrategyUpdateStrategyDataSourceConfig = "/sovereign.api.v1.Strategy/UpdateStrategyDataSourceConfig"
const OperationStrategyUpdateStrategyDialTestConfig = "/sovereign.api.v1.Strategy/UpdateStrategyDialTestConfig"
const OperationStrategyUpdateStrategyGroup = "/sovereign.api.v1.Strategy/UpdateStrategyGroup"
const OperationStrategyUpdateStrategyGroupStatus = "/sovereign.api.v1.Strategy/UpdateStrategyGroupStatus"
const OperationStrategyUpdateStrategyGroupUpgradeConfig = "/sovereign.api.v1.Strategy/UpdateStrategyGroupUpgradeConfig"
const OperationStrategyUpdateStrategyGroupUpgradeMode = "/sovereign.api.v1.Strategy/UpdateStrategyGroupUpgradeMode"
const OperationStrategyUpdateStrategyNotifyConfig = "/sovereign.api.v1.Strategy/UpdateStrategyNotifyConfig"
const OperationStrategyUpdateStrategyRule = "/sovereign.api.v1.Strategy/UpdateStrategyRule"
const OperationStrategyUpdateStrategyRuleStatus = "/sovereign.api.v1.Strategy/UpdateStrategyRuleStatus"
const OperationStrategyUpdateStrategyStatus = "/sovereign.api.v1.Strategy/UpdateStrategyStatus"
const OperationStrategyUpdateStrategySuppressConfig = "/sovereign.api.v1.Strategy/UpdateStrategySuppressConfig"

type StrategyHTTPServer interface {
	AddStrategyToGroup(context.Context, *AddStrategyToGroupRequest) (*AddStrategyToGroupReply, error)
	// CreateReceiver 接收对象相关接口
	CreateReceiver(context.Context, *CreateReceiverRequest) (*CreateReceiverReply, error)
	CreateStrategy(context.Context, *CreateStrategyRequest) (*CreateStrategyReply, error)
	// CreateStrategyGroup 策略分组相关接口
	CreateStrategyGroup(context.Context, *CreateStrategyGroupRequest) (*CreateStrategyGroupReply, error)
	// CreateStrategyRule 策略规则相关接口
	CreateStrategyRule(context.Context, *CreateStrategyRuleRequest) (*CreateStrategyRuleReply, error)
	DeleteReceiver(context.Context, *DeleteReceiverRequest) (*DeleteReceiverReply, error)
	DeleteStrategy(context.Context, *DeleteStrategyRequest) (*DeleteStrategyReply, error)
	DeleteStrategyGroup(context.Context, *DeleteStrategyGroupRequest) (*DeleteStrategyGroupReply, error)
	DeleteStrategyRule(context.Context, *DeleteStrategyRuleRequest) (*DeleteStrategyRuleReply, error)
	GetGroupStrategies(context.Context, *GetGroupStrategiesRequest) (*ListStrategyReply, error)
	GetReceiver(context.Context, *GetReceiverRequest) (*ReceiverItem, error)
	GetStrategy(context.Context, *GetStrategyRequest) (*StrategyItem, error)
	GetStrategyGroup(context.Context, *GetStrategyGroupRequest) (*StrategyGroupItem, error)
	GetStrategyRule(context.Context, *GetStrategyRuleRequest) (*StrategyRuleItem, error)
	ListReceiver(context.Context, *ListReceiverRequest) (*ListReceiverReply, error)
	ListStrategy(context.Context, *ListStrategyRequest) (*ListStrategyReply, error)
	ListStrategyGroup(context.Context, *ListStrategyGroupRequest) (*ListStrategyGroupReply, error)
	ListStrategyRule(context.Context, *ListStrategyRuleRequest) (*ListStrategyRuleReply, error)
	RemoveStrategyFromGroup(context.Context, *RemoveStrategyFromGroupRequest) (*RemoveStrategyFromGroupReply, error)
	SelectStrategy(context.Context, *SelectStrategyRequest) (*SelectStrategyReply, error)
	UpdateReceiver(context.Context, *UpdateReceiverRequest) (*UpdateReceiverReply, error)
	UpdateStrategy(context.Context, *UpdateStrategyRequest) (*UpdateStrategyReply, error)
	UpdateStrategyAlertConfig(context.Context, *UpdateStrategyAlertConfigRequest) (*UpdateStrategyAlertConfigReply, error)
	// UpdateStrategyDataSourceConfig 策略详细配置更新接口
	UpdateStrategyDataSourceConfig(context.Context, *UpdateStrategyDataSourceConfigRequest) (*UpdateStrategyDataSourceConfigReply, error)
	UpdateStrategyDialTestConfig(context.Context, *UpdateStrategyDialTestConfigRequest) (*UpdateStrategyDialTestConfigReply, error)
	UpdateStrategyGroup(context.Context, *UpdateStrategyGroupRequest) (*UpdateStrategyGroupReply, error)
	UpdateStrategyGroupStatus(context.Context, *UpdateStrategyGroupStatusRequest) (*UpdateStrategyGroupStatusReply, error)
	UpdateStrategyGroupUpgradeConfig(context.Context, *UpdateStrategyGroupUpgradeConfigRequest) (*UpdateStrategyGroupUpgradeConfigReply, error)
	// UpdateStrategyGroupUpgradeMode 策略组升级模式更新接口
	UpdateStrategyGroupUpgradeMode(context.Context, *UpdateStrategyGroupUpgradeModeRequest) (*UpdateStrategyGroupUpgradeModeReply, error)
	UpdateStrategyNotifyConfig(context.Context, *UpdateStrategyNotifyConfigRequest) (*UpdateStrategyNotifyConfigReply, error)
	UpdateStrategyRule(context.Context, *UpdateStrategyRuleRequest) (*UpdateStrategyRuleReply, error)
	UpdateStrategyRuleStatus(context.Context, *UpdateStrategyRuleStatusRequest) (*UpdateStrategyRuleStatusReply, error)
	UpdateStrategyStatus(context.Context, *UpdateStrategyStatusRequest) (*UpdateStrategyStatusReply, error)
	UpdateStrategySuppressConfig(context.Context, *UpdateStrategySuppressConfigRequest) (*UpdateStrategySuppressConfigReply, error)
}

func RegisterStrategyHTTPServer(s *http.Server, srv StrategyHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/strategy", _Strategy_CreateStrategy0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/{uid}", _Strategy_UpdateStrategy0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/{uid}/status", _Strategy_UpdateStrategyStatus0_HTTP_Handler(srv))
	r.DELETE("/v1/strategy/{uid}", _Strategy_DeleteStrategy0_HTTP_Handler(srv))
	r.GET("/v1/strategy/{uid}", _Strategy_GetStrategy0_HTTP_Handler(srv))
	r.GET("/v1/strategies", _Strategy_ListStrategy0_HTTP_Handler(srv))
	r.GET("/v1/strategies/select", _Strategy_SelectStrategy0_HTTP_Handler(srv))
	r.POST("/v1/strategy/group", _Strategy_CreateStrategyGroup0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/group/{uid}", _Strategy_UpdateStrategyGroup0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/group/{uid}/status", _Strategy_UpdateStrategyGroupStatus0_HTTP_Handler(srv))
	r.DELETE("/v1/strategy/group/{uid}", _Strategy_DeleteStrategyGroup0_HTTP_Handler(srv))
	r.GET("/v1/strategy/group/{uid}", _Strategy_GetStrategyGroup0_HTTP_Handler(srv))
	r.GET("/v1/strategy/groups", _Strategy_ListStrategyGroup0_HTTP_Handler(srv))
	r.GET("/v1/strategy/group/{group_uid}/strategies", _Strategy_GetGroupStrategies0_HTTP_Handler(srv))
	r.POST("/v1/strategy/group/{group_uid}/strategy/{strategy_uid}", _Strategy_AddStrategyToGroup0_HTTP_Handler(srv))
	r.DELETE("/v1/strategy/group/{group_uid}/strategy/{strategy_uid}", _Strategy_RemoveStrategyFromGroup0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/group/{uid}/upgrade-mode", _Strategy_UpdateStrategyGroupUpgradeMode0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/group/{uid}/upgrade-config", _Strategy_UpdateStrategyGroupUpgradeConfig0_HTTP_Handler(srv))
	r.POST("/v1/receiver", _Strategy_CreateReceiver0_HTTP_Handler(srv))
	r.PUT("/v1/receiver/{uid}", _Strategy_UpdateReceiver0_HTTP_Handler(srv))
	r.DELETE("/v1/receiver/{uid}", _Strategy_DeleteReceiver0_HTTP_Handler(srv))
	r.GET("/v1/receiver/{uid}", _Strategy_GetReceiver0_HTTP_Handler(srv))
	r.GET("/v1/receivers", _Strategy_ListReceiver0_HTTP_Handler(srv))
	r.POST("/v1/strategy/{strategy_uid}/rule", _Strategy_CreateStrategyRule0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/rule/{uid}", _Strategy_UpdateStrategyRule0_HTTP_Handler(srv))
	r.DELETE("/v1/strategy/rule/{uid}", _Strategy_DeleteStrategyRule0_HTTP_Handler(srv))
	r.GET("/v1/strategy/rule/{uid}", _Strategy_GetStrategyRule0_HTTP_Handler(srv))
	r.GET("/v1/strategy/{strategy_uid}/rules", _Strategy_ListStrategyRule0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/rule/{uid}/status", _Strategy_UpdateStrategyRuleStatus0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/{uid}/datasource-config", _Strategy_UpdateStrategyDataSourceConfig0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/{uid}/alert-config", _Strategy_UpdateStrategyAlertConfig0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/{uid}/notify-config", _Strategy_UpdateStrategyNotifyConfig0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/{uid}/dial-test-config", _Strategy_UpdateStrategyDialTestConfig0_HTTP_Handler(srv))
	r.PUT("/v1/strategy/{uid}/suppress-config", _Strategy_UpdateStrategySuppressConfig0_HTTP_Handler(srv))
}

func _Strategy_CreateStrategy0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateStrategyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyCreateStrategy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateStrategy(ctx, req.(*CreateStrategyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateStrategyReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategy0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategy(ctx, req.(*UpdateStrategyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyStatus0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyStatus(ctx, req.(*UpdateStrategyStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_DeleteStrategy0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteStrategyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyDeleteStrategy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteStrategy(ctx, req.(*DeleteStrategyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteStrategyReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_GetStrategy0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStrategyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyGetStrategy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStrategy(ctx, req.(*GetStrategyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StrategyItem)
		return ctx.Result(200, reply)
	}
}

func _Strategy_ListStrategy0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStrategyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyListStrategy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStrategy(ctx, req.(*ListStrategyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListStrategyReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_SelectStrategy0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SelectStrategyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategySelectStrategy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SelectStrategy(ctx, req.(*SelectStrategyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SelectStrategyReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_CreateStrategyGroup0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateStrategyGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyCreateStrategyGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateStrategyGroup(ctx, req.(*CreateStrategyGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateStrategyGroupReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyGroup0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyGroup(ctx, req.(*UpdateStrategyGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyGroupReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyGroupStatus0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyGroupStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyGroupStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyGroupStatus(ctx, req.(*UpdateStrategyGroupStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyGroupStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_DeleteStrategyGroup0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteStrategyGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyDeleteStrategyGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteStrategyGroup(ctx, req.(*DeleteStrategyGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteStrategyGroupReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_GetStrategyGroup0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStrategyGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyGetStrategyGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStrategyGroup(ctx, req.(*GetStrategyGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StrategyGroupItem)
		return ctx.Result(200, reply)
	}
}

func _Strategy_ListStrategyGroup0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStrategyGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyListStrategyGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStrategyGroup(ctx, req.(*ListStrategyGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListStrategyGroupReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_GetGroupStrategies0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGroupStrategiesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyGetGroupStrategies)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGroupStrategies(ctx, req.(*GetGroupStrategiesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListStrategyReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_AddStrategyToGroup0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddStrategyToGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyAddStrategyToGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddStrategyToGroup(ctx, req.(*AddStrategyToGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddStrategyToGroupReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_RemoveStrategyFromGroup0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveStrategyFromGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyRemoveStrategyFromGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveStrategyFromGroup(ctx, req.(*RemoveStrategyFromGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveStrategyFromGroupReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyGroupUpgradeMode0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyGroupUpgradeModeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyGroupUpgradeMode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyGroupUpgradeMode(ctx, req.(*UpdateStrategyGroupUpgradeModeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyGroupUpgradeModeReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyGroupUpgradeConfig0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyGroupUpgradeConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyGroupUpgradeConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyGroupUpgradeConfig(ctx, req.(*UpdateStrategyGroupUpgradeConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyGroupUpgradeConfigReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_CreateReceiver0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateReceiverRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyCreateReceiver)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateReceiver(ctx, req.(*CreateReceiverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateReceiverReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateReceiver0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateReceiverRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateReceiver)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateReceiver(ctx, req.(*UpdateReceiverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateReceiverReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_DeleteReceiver0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteReceiverRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyDeleteReceiver)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteReceiver(ctx, req.(*DeleteReceiverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteReceiverReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_GetReceiver0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReceiverRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyGetReceiver)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReceiver(ctx, req.(*GetReceiverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReceiverItem)
		return ctx.Result(200, reply)
	}
}

func _Strategy_ListReceiver0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReceiverRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyListReceiver)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReceiver(ctx, req.(*ListReceiverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReceiverReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_CreateStrategyRule0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateStrategyRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyCreateStrategyRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateStrategyRule(ctx, req.(*CreateStrategyRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateStrategyRuleReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyRule0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyRule(ctx, req.(*UpdateStrategyRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyRuleReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_DeleteStrategyRule0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteStrategyRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyDeleteStrategyRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteStrategyRule(ctx, req.(*DeleteStrategyRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteStrategyRuleReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_GetStrategyRule0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStrategyRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyGetStrategyRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStrategyRule(ctx, req.(*GetStrategyRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StrategyRuleItem)
		return ctx.Result(200, reply)
	}
}

func _Strategy_ListStrategyRule0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStrategyRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyListStrategyRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStrategyRule(ctx, req.(*ListStrategyRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListStrategyRuleReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyRuleStatus0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyRuleStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyRuleStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyRuleStatus(ctx, req.(*UpdateStrategyRuleStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyRuleStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyDataSourceConfig0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyDataSourceConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyDataSourceConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyDataSourceConfig(ctx, req.(*UpdateStrategyDataSourceConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyDataSourceConfigReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyAlertConfig0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyAlertConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyAlertConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyAlertConfig(ctx, req.(*UpdateStrategyAlertConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyAlertConfigReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyNotifyConfig0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyNotifyConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyNotifyConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyNotifyConfig(ctx, req.(*UpdateStrategyNotifyConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyNotifyConfigReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategyDialTestConfig0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategyDialTestConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategyDialTestConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategyDialTestConfig(ctx, req.(*UpdateStrategyDialTestConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategyDialTestConfigReply)
		return ctx.Result(200, reply)
	}
}

func _Strategy_UpdateStrategySuppressConfig0_HTTP_Handler(srv StrategyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStrategySuppressConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStrategyUpdateStrategySuppressConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStrategySuppressConfig(ctx, req.(*UpdateStrategySuppressConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStrategySuppressConfigReply)
		return ctx.Result(200, reply)
	}
}

type StrategyHTTPClient interface {
	AddStrategyToGroup(ctx context.Context, req *AddStrategyToGroupRequest, opts ...http.CallOption) (rsp *AddStrategyToGroupReply, err error)
	// CreateReceiver 接收对象相关接口
	CreateReceiver(ctx context.Context, req *CreateReceiverRequest, opts ...http.CallOption) (rsp *CreateReceiverReply, err error)
	CreateStrategy(ctx context.Context, req *CreateStrategyRequest, opts ...http.CallOption) (rsp *CreateStrategyReply, err error)
	// CreateStrategyGroup 策略分组相关接口
	CreateStrategyGroup(ctx context.Context, req *CreateStrategyGroupRequest, opts ...http.CallOption) (rsp *CreateStrategyGroupReply, err error)
	// CreateStrategyRule 策略规则相关接口
	CreateStrategyRule(ctx context.Context, req *CreateStrategyRuleRequest, opts ...http.CallOption) (rsp *CreateStrategyRuleReply, err error)
	DeleteReceiver(ctx context.Context, req *DeleteReceiverRequest, opts ...http.CallOption) (rsp *DeleteReceiverReply, err error)
	DeleteStrategy(ctx context.Context, req *DeleteStrategyRequest, opts ...http.CallOption) (rsp *DeleteStrategyReply, err error)
	DeleteStrategyGroup(ctx context.Context, req *DeleteStrategyGroupRequest, opts ...http.CallOption) (rsp *DeleteStrategyGroupReply, err error)
	DeleteStrategyRule(ctx context.Context, req *DeleteStrategyRuleRequest, opts ...http.CallOption) (rsp *DeleteStrategyRuleReply, err error)
	GetGroupStrategies(ctx context.Context, req *GetGroupStrategiesRequest, opts ...http.CallOption) (rsp *ListStrategyReply, err error)
	GetReceiver(ctx context.Context, req *GetReceiverRequest, opts ...http.CallOption) (rsp *ReceiverItem, err error)
	GetStrategy(ctx context.Context, req *GetStrategyRequest, opts ...http.CallOption) (rsp *StrategyItem, err error)
	GetStrategyGroup(ctx context.Context, req *GetStrategyGroupRequest, opts ...http.CallOption) (rsp *StrategyGroupItem, err error)
	GetStrategyRule(ctx context.Context, req *GetStrategyRuleRequest, opts ...http.CallOption) (rsp *StrategyRuleItem, err error)
	ListReceiver(ctx context.Context, req *ListReceiverRequest, opts ...http.CallOption) (rsp *ListReceiverReply, err error)
	ListStrategy(ctx context.Context, req *ListStrategyRequest, opts ...http.CallOption) (rsp *ListStrategyReply, err error)
	ListStrategyGroup(ctx context.Context, req *ListStrategyGroupRequest, opts ...http.CallOption) (rsp *ListStrategyGroupReply, err error)
	ListStrategyRule(ctx context.Context, req *ListStrategyRuleRequest, opts ...http.CallOption) (rsp *ListStrategyRuleReply, err error)
	RemoveStrategyFromGroup(ctx context.Context, req *RemoveStrategyFromGroupRequest, opts ...http.CallOption) (rsp *RemoveStrategyFromGroupReply, err error)
	SelectStrategy(ctx context.Context, req *SelectStrategyRequest, opts ...http.CallOption) (rsp *SelectStrategyReply, err error)
	UpdateReceiver(ctx context.Context, req *UpdateReceiverRequest, opts ...http.CallOption) (rsp *UpdateReceiverReply, err error)
	UpdateStrategy(ctx context.Context, req *UpdateStrategyRequest, opts ...http.CallOption) (rsp *UpdateStrategyReply, err error)
	UpdateStrategyAlertConfig(ctx context.Context, req *UpdateStrategyAlertConfigRequest, opts ...http.CallOption) (rsp *UpdateStrategyAlertConfigReply, err error)
	// UpdateStrategyDataSourceConfig 策略详细配置更新接口
	UpdateStrategyDataSourceConfig(ctx context.Context, req *UpdateStrategyDataSourceConfigRequest, opts ...http.CallOption) (rsp *UpdateStrategyDataSourceConfigReply, err error)
	UpdateStrategyDialTestConfig(ctx context.Context, req *UpdateStrategyDialTestConfigRequest, opts ...http.CallOption) (rsp *UpdateStrategyDialTestConfigReply, err error)
	UpdateStrategyGroup(ctx context.Context, req *UpdateStrategyGroupRequest, opts ...http.CallOption) (rsp *UpdateStrategyGroupReply, err error)
	UpdateStrategyGroupStatus(ctx context.Context, req *UpdateStrategyGroupStatusRequest, opts ...http.CallOption) (rsp *UpdateStrategyGroupStatusReply, err error)
	UpdateStrategyGroupUpgradeConfig(ctx context.Context, req *UpdateStrategyGroupUpgradeConfigRequest, opts ...http.CallOption) (rsp *UpdateStrategyGroupUpgradeConfigReply, err error)
	// UpdateStrategyGroupUpgradeMode 策略组升级模式更新接口
	UpdateStrategyGroupUpgradeMode(ctx context.Context, req *UpdateStrategyGroupUpgradeModeRequest, opts ...http.CallOption) (rsp *UpdateStrategyGroupUpgradeModeReply, err error)
	UpdateStrategyNotifyConfig(ctx context.Context, req *UpdateStrategyNotifyConfigRequest, opts ...http.CallOption) (rsp *UpdateStrategyNotifyConfigReply, err error)
	UpdateStrategyRule(ctx context.Context, req *UpdateStrategyRuleRequest, opts ...http.CallOption) (rsp *UpdateStrategyRuleReply, err error)
	UpdateStrategyRuleStatus(ctx context.Context, req *UpdateStrategyRuleStatusRequest, opts ...http.CallOption) (rsp *UpdateStrategyRuleStatusReply, err error)
	UpdateStrategyStatus(ctx context.Context, req *UpdateStrategyStatusRequest, opts ...http.CallOption) (rsp *UpdateStrategyStatusReply, err error)
	UpdateStrategySuppressConfig(ctx context.Context, req *UpdateStrategySuppressConfigRequest, opts ...http.CallOption) (rsp *UpdateStrategySuppressConfigReply, err error)
}

type StrategyHTTPClientImpl struct {
	cc *http.Client
}

func NewStrategyHTTPClient(client *http.Client) StrategyHTTPClient {
	return &StrategyHTTPClientImpl{client}
}

func (c *StrategyHTTPClientImpl) AddStrategyToGroup(ctx context.Context, in *AddStrategyToGroupRequest, opts ...http.CallOption) (*AddStrategyToGroupReply, error) {
	var out AddStrategyToGroupReply
	pattern := "/v1/strategy/group/{group_uid}/strategy/{strategy_uid}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyAddStrategyToGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateReceiver 接收对象相关接口
func (c *StrategyHTTPClientImpl) CreateReceiver(ctx context.Context, in *CreateReceiverRequest, opts ...http.CallOption) (*CreateReceiverReply, error) {
	var out CreateReceiverReply
	pattern := "/v1/receiver"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyCreateReceiver))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...http.CallOption) (*CreateStrategyReply, error) {
	var out CreateStrategyReply
	pattern := "/v1/strategy"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyCreateStrategy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateStrategyGroup 策略分组相关接口
func (c *StrategyHTTPClientImpl) CreateStrategyGroup(ctx context.Context, in *CreateStrategyGroupRequest, opts ...http.CallOption) (*CreateStrategyGroupReply, error) {
	var out CreateStrategyGroupReply
	pattern := "/v1/strategy/group"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyCreateStrategyGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateStrategyRule 策略规则相关接口
func (c *StrategyHTTPClientImpl) CreateStrategyRule(ctx context.Context, in *CreateStrategyRuleRequest, opts ...http.CallOption) (*CreateStrategyRuleReply, error) {
	var out CreateStrategyRuleReply
	pattern := "/v1/strategy/{strategy_uid}/rule"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyCreateStrategyRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) DeleteReceiver(ctx context.Context, in *DeleteReceiverRequest, opts ...http.CallOption) (*DeleteReceiverReply, error) {
	var out DeleteReceiverReply
	pattern := "/v1/receiver/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyDeleteReceiver))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...http.CallOption) (*DeleteStrategyReply, error) {
	var out DeleteStrategyReply
	pattern := "/v1/strategy/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyDeleteStrategy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) DeleteStrategyGroup(ctx context.Context, in *DeleteStrategyGroupRequest, opts ...http.CallOption) (*DeleteStrategyGroupReply, error) {
	var out DeleteStrategyGroupReply
	pattern := "/v1/strategy/group/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyDeleteStrategyGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) DeleteStrategyRule(ctx context.Context, in *DeleteStrategyRuleRequest, opts ...http.CallOption) (*DeleteStrategyRuleReply, error) {
	var out DeleteStrategyRuleReply
	pattern := "/v1/strategy/rule/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyDeleteStrategyRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) GetGroupStrategies(ctx context.Context, in *GetGroupStrategiesRequest, opts ...http.CallOption) (*ListStrategyReply, error) {
	var out ListStrategyReply
	pattern := "/v1/strategy/group/{group_uid}/strategies"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyGetGroupStrategies))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) GetReceiver(ctx context.Context, in *GetReceiverRequest, opts ...http.CallOption) (*ReceiverItem, error) {
	var out ReceiverItem
	pattern := "/v1/receiver/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyGetReceiver))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...http.CallOption) (*StrategyItem, error) {
	var out StrategyItem
	pattern := "/v1/strategy/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyGetStrategy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) GetStrategyGroup(ctx context.Context, in *GetStrategyGroupRequest, opts ...http.CallOption) (*StrategyGroupItem, error) {
	var out StrategyGroupItem
	pattern := "/v1/strategy/group/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyGetStrategyGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) GetStrategyRule(ctx context.Context, in *GetStrategyRuleRequest, opts ...http.CallOption) (*StrategyRuleItem, error) {
	var out StrategyRuleItem
	pattern := "/v1/strategy/rule/{uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyGetStrategyRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) ListReceiver(ctx context.Context, in *ListReceiverRequest, opts ...http.CallOption) (*ListReceiverReply, error) {
	var out ListReceiverReply
	pattern := "/v1/receivers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyListReceiver))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) ListStrategy(ctx context.Context, in *ListStrategyRequest, opts ...http.CallOption) (*ListStrategyReply, error) {
	var out ListStrategyReply
	pattern := "/v1/strategies"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyListStrategy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) ListStrategyGroup(ctx context.Context, in *ListStrategyGroupRequest, opts ...http.CallOption) (*ListStrategyGroupReply, error) {
	var out ListStrategyGroupReply
	pattern := "/v1/strategy/groups"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyListStrategyGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) ListStrategyRule(ctx context.Context, in *ListStrategyRuleRequest, opts ...http.CallOption) (*ListStrategyRuleReply, error) {
	var out ListStrategyRuleReply
	pattern := "/v1/strategy/{strategy_uid}/rules"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyListStrategyRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) RemoveStrategyFromGroup(ctx context.Context, in *RemoveStrategyFromGroupRequest, opts ...http.CallOption) (*RemoveStrategyFromGroupReply, error) {
	var out RemoveStrategyFromGroupReply
	pattern := "/v1/strategy/group/{group_uid}/strategy/{strategy_uid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategyRemoveStrategyFromGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) SelectStrategy(ctx context.Context, in *SelectStrategyRequest, opts ...http.CallOption) (*SelectStrategyReply, error) {
	var out SelectStrategyReply
	pattern := "/v1/strategies/select"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStrategySelectStrategy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateReceiver(ctx context.Context, in *UpdateReceiverRequest, opts ...http.CallOption) (*UpdateReceiverReply, error) {
	var out UpdateReceiverReply
	pattern := "/v1/receiver/{uid}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateReceiver))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...http.CallOption) (*UpdateStrategyReply, error) {
	var out UpdateStrategyReply
	pattern := "/v1/strategy/{uid}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategyAlertConfig(ctx context.Context, in *UpdateStrategyAlertConfigRequest, opts ...http.CallOption) (*UpdateStrategyAlertConfigReply, error) {
	var out UpdateStrategyAlertConfigReply
	pattern := "/v1/strategy/{uid}/alert-config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyAlertConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateStrategyDataSourceConfig 策略详细配置更新接口
func (c *StrategyHTTPClientImpl) UpdateStrategyDataSourceConfig(ctx context.Context, in *UpdateStrategyDataSourceConfigRequest, opts ...http.CallOption) (*UpdateStrategyDataSourceConfigReply, error) {
	var out UpdateStrategyDataSourceConfigReply
	pattern := "/v1/strategy/{uid}/datasource-config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyDataSourceConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategyDialTestConfig(ctx context.Context, in *UpdateStrategyDialTestConfigRequest, opts ...http.CallOption) (*UpdateStrategyDialTestConfigReply, error) {
	var out UpdateStrategyDialTestConfigReply
	pattern := "/v1/strategy/{uid}/dial-test-config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyDialTestConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategyGroup(ctx context.Context, in *UpdateStrategyGroupRequest, opts ...http.CallOption) (*UpdateStrategyGroupReply, error) {
	var out UpdateStrategyGroupReply
	pattern := "/v1/strategy/group/{uid}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategyGroupStatus(ctx context.Context, in *UpdateStrategyGroupStatusRequest, opts ...http.CallOption) (*UpdateStrategyGroupStatusReply, error) {
	var out UpdateStrategyGroupStatusReply
	pattern := "/v1/strategy/group/{uid}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyGroupStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategyGroupUpgradeConfig(ctx context.Context, in *UpdateStrategyGroupUpgradeConfigRequest, opts ...http.CallOption) (*UpdateStrategyGroupUpgradeConfigReply, error) {
	var out UpdateStrategyGroupUpgradeConfigReply
	pattern := "/v1/strategy/group/{uid}/upgrade-config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyGroupUpgradeConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateStrategyGroupUpgradeMode 策略组升级模式更新接口
func (c *StrategyHTTPClientImpl) UpdateStrategyGroupUpgradeMode(ctx context.Context, in *UpdateStrategyGroupUpgradeModeRequest, opts ...http.CallOption) (*UpdateStrategyGroupUpgradeModeReply, error) {
	var out UpdateStrategyGroupUpgradeModeReply
	pattern := "/v1/strategy/group/{uid}/upgrade-mode"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyGroupUpgradeMode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategyNotifyConfig(ctx context.Context, in *UpdateStrategyNotifyConfigRequest, opts ...http.CallOption) (*UpdateStrategyNotifyConfigReply, error) {
	var out UpdateStrategyNotifyConfigReply
	pattern := "/v1/strategy/{uid}/notify-config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyNotifyConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategyRule(ctx context.Context, in *UpdateStrategyRuleRequest, opts ...http.CallOption) (*UpdateStrategyRuleReply, error) {
	var out UpdateStrategyRuleReply
	pattern := "/v1/strategy/rule/{uid}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategyRuleStatus(ctx context.Context, in *UpdateStrategyRuleStatusRequest, opts ...http.CallOption) (*UpdateStrategyRuleStatusReply, error) {
	var out UpdateStrategyRuleStatusReply
	pattern := "/v1/strategy/rule/{uid}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyRuleStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategyStatus(ctx context.Context, in *UpdateStrategyStatusRequest, opts ...http.CallOption) (*UpdateStrategyStatusReply, error) {
	var out UpdateStrategyStatusReply
	pattern := "/v1/strategy/{uid}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategyStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StrategyHTTPClientImpl) UpdateStrategySuppressConfig(ctx context.Context, in *UpdateStrategySuppressConfigRequest, opts ...http.CallOption) (*UpdateStrategySuppressConfigReply, error) {
	var out UpdateStrategySuppressConfigReply
	pattern := "/v1/strategy/{uid}/suppress-config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStrategyUpdateStrategySuppressConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
