// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/v1/subscription.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subscription_CreateSubscription_FullMethodName               = "/sovereign.api.v1.Subscription/CreateSubscription"
	Subscription_UpdateSubscription_FullMethodName               = "/sovereign.api.v1.Subscription/UpdateSubscription"
	Subscription_UpdateSubscriptionStatus_FullMethodName         = "/sovereign.api.v1.Subscription/UpdateSubscriptionStatus"
	Subscription_DeleteSubscription_FullMethodName               = "/sovereign.api.v1.Subscription/DeleteSubscription"
	Subscription_GetSubscription_FullMethodName                  = "/sovereign.api.v1.Subscription/GetSubscription"
	Subscription_ListSubscription_FullMethodName                 = "/sovereign.api.v1.Subscription/ListSubscription"
	Subscription_SelectSubscription_FullMethodName               = "/sovereign.api.v1.Subscription/SelectSubscription"
	Subscription_UpdateSubscriptionStrategyGroups_FullMethodName = "/sovereign.api.v1.Subscription/UpdateSubscriptionStrategyGroups"
	Subscription_UpdateSubscriptionDataSources_FullMethodName    = "/sovereign.api.v1.Subscription/UpdateSubscriptionDataSources"
	Subscription_UpdateSubscriptionAlertLevels_FullMethodName    = "/sovereign.api.v1.Subscription/UpdateSubscriptionAlertLevels"
	Subscription_UpdateSubscriptionNotifyTypes_FullMethodName    = "/sovereign.api.v1.Subscription/UpdateSubscriptionNotifyTypes"
)

// SubscriptionClient is the client API for Subscription service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionClient interface {
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionReply, error)
	UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionReply, error)
	UpdateSubscriptionStatus(ctx context.Context, in *UpdateSubscriptionStatusRequest, opts ...grpc.CallOption) (*UpdateSubscriptionStatusReply, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionReply, error)
	GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionItem, error)
	ListSubscription(ctx context.Context, in *ListSubscriptionRequest, opts ...grpc.CallOption) (*ListSubscriptionReply, error)
	SelectSubscription(ctx context.Context, in *SelectSubscriptionRequest, opts ...grpc.CallOption) (*SelectSubscriptionReply, error)
	UpdateSubscriptionStrategyGroups(ctx context.Context, in *UpdateSubscriptionStrategyGroupsRequest, opts ...grpc.CallOption) (*UpdateSubscriptionStrategyGroupsReply, error)
	UpdateSubscriptionDataSources(ctx context.Context, in *UpdateSubscriptionDataSourcesRequest, opts ...grpc.CallOption) (*UpdateSubscriptionDataSourcesReply, error)
	UpdateSubscriptionAlertLevels(ctx context.Context, in *UpdateSubscriptionAlertLevelsRequest, opts ...grpc.CallOption) (*UpdateSubscriptionAlertLevelsReply, error)
	UpdateSubscriptionNotifyTypes(ctx context.Context, in *UpdateSubscriptionNotifyTypesRequest, opts ...grpc.CallOption) (*UpdateSubscriptionNotifyTypesReply, error)
}

type subscriptionClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionClient(cc grpc.ClientConnInterface) SubscriptionClient {
	return &subscriptionClient{cc}
}

func (c *subscriptionClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubscriptionReply)
	err := c.cc.Invoke(ctx, Subscription_CreateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubscriptionReply)
	err := c.cc.Invoke(ctx, Subscription_UpdateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) UpdateSubscriptionStatus(ctx context.Context, in *UpdateSubscriptionStatusRequest, opts ...grpc.CallOption) (*UpdateSubscriptionStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubscriptionStatusReply)
	err := c.cc.Invoke(ctx, Subscription_UpdateSubscriptionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSubscriptionReply)
	err := c.cc.Invoke(ctx, Subscription_DeleteSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionItem)
	err := c.cc.Invoke(ctx, Subscription_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) ListSubscription(ctx context.Context, in *ListSubscriptionRequest, opts ...grpc.CallOption) (*ListSubscriptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubscriptionReply)
	err := c.cc.Invoke(ctx, Subscription_ListSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) SelectSubscription(ctx context.Context, in *SelectSubscriptionRequest, opts ...grpc.CallOption) (*SelectSubscriptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectSubscriptionReply)
	err := c.cc.Invoke(ctx, Subscription_SelectSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) UpdateSubscriptionStrategyGroups(ctx context.Context, in *UpdateSubscriptionStrategyGroupsRequest, opts ...grpc.CallOption) (*UpdateSubscriptionStrategyGroupsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubscriptionStrategyGroupsReply)
	err := c.cc.Invoke(ctx, Subscription_UpdateSubscriptionStrategyGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) UpdateSubscriptionDataSources(ctx context.Context, in *UpdateSubscriptionDataSourcesRequest, opts ...grpc.CallOption) (*UpdateSubscriptionDataSourcesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubscriptionDataSourcesReply)
	err := c.cc.Invoke(ctx, Subscription_UpdateSubscriptionDataSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) UpdateSubscriptionAlertLevels(ctx context.Context, in *UpdateSubscriptionAlertLevelsRequest, opts ...grpc.CallOption) (*UpdateSubscriptionAlertLevelsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubscriptionAlertLevelsReply)
	err := c.cc.Invoke(ctx, Subscription_UpdateSubscriptionAlertLevels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) UpdateSubscriptionNotifyTypes(ctx context.Context, in *UpdateSubscriptionNotifyTypesRequest, opts ...grpc.CallOption) (*UpdateSubscriptionNotifyTypesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubscriptionNotifyTypesReply)
	err := c.cc.Invoke(ctx, Subscription_UpdateSubscriptionNotifyTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionServer is the server API for Subscription service.
// All implementations must embed UnimplementedSubscriptionServer
// for forward compatibility.
type SubscriptionServer interface {
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionReply, error)
	UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*UpdateSubscriptionReply, error)
	UpdateSubscriptionStatus(context.Context, *UpdateSubscriptionStatusRequest) (*UpdateSubscriptionStatusReply, error)
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionReply, error)
	GetSubscription(context.Context, *GetSubscriptionRequest) (*SubscriptionItem, error)
	ListSubscription(context.Context, *ListSubscriptionRequest) (*ListSubscriptionReply, error)
	SelectSubscription(context.Context, *SelectSubscriptionRequest) (*SelectSubscriptionReply, error)
	UpdateSubscriptionStrategyGroups(context.Context, *UpdateSubscriptionStrategyGroupsRequest) (*UpdateSubscriptionStrategyGroupsReply, error)
	UpdateSubscriptionDataSources(context.Context, *UpdateSubscriptionDataSourcesRequest) (*UpdateSubscriptionDataSourcesReply, error)
	UpdateSubscriptionAlertLevels(context.Context, *UpdateSubscriptionAlertLevelsRequest) (*UpdateSubscriptionAlertLevelsReply, error)
	UpdateSubscriptionNotifyTypes(context.Context, *UpdateSubscriptionNotifyTypesRequest) (*UpdateSubscriptionNotifyTypesReply, error)
	mustEmbedUnimplementedSubscriptionServer()
}

// UnimplementedSubscriptionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionServer struct{}

func (UnimplementedSubscriptionServer) CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedSubscriptionServer) UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*UpdateSubscriptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscription not implemented")
}
func (UnimplementedSubscriptionServer) UpdateSubscriptionStatus(context.Context, *UpdateSubscriptionStatusRequest) (*UpdateSubscriptionStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscriptionStatus not implemented")
}
func (UnimplementedSubscriptionServer) DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedSubscriptionServer) GetSubscription(context.Context, *GetSubscriptionRequest) (*SubscriptionItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedSubscriptionServer) ListSubscription(context.Context, *ListSubscriptionRequest) (*ListSubscriptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubscription not implemented")
}
func (UnimplementedSubscriptionServer) SelectSubscription(context.Context, *SelectSubscriptionRequest) (*SelectSubscriptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectSubscription not implemented")
}
func (UnimplementedSubscriptionServer) UpdateSubscriptionStrategyGroups(context.Context, *UpdateSubscriptionStrategyGroupsRequest) (*UpdateSubscriptionStrategyGroupsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscriptionStrategyGroups not implemented")
}
func (UnimplementedSubscriptionServer) UpdateSubscriptionDataSources(context.Context, *UpdateSubscriptionDataSourcesRequest) (*UpdateSubscriptionDataSourcesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscriptionDataSources not implemented")
}
func (UnimplementedSubscriptionServer) UpdateSubscriptionAlertLevels(context.Context, *UpdateSubscriptionAlertLevelsRequest) (*UpdateSubscriptionAlertLevelsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscriptionAlertLevels not implemented")
}
func (UnimplementedSubscriptionServer) UpdateSubscriptionNotifyTypes(context.Context, *UpdateSubscriptionNotifyTypesRequest) (*UpdateSubscriptionNotifyTypesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscriptionNotifyTypes not implemented")
}
func (UnimplementedSubscriptionServer) mustEmbedUnimplementedSubscriptionServer() {}
func (UnimplementedSubscriptionServer) testEmbeddedByValue()                      {}

// UnsafeSubscriptionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServer will
// result in compilation errors.
type UnsafeSubscriptionServer interface {
	mustEmbedUnimplementedSubscriptionServer()
}

func RegisterSubscriptionServer(s grpc.ServiceRegistrar, srv SubscriptionServer) {
	// If the following call pancis, it indicates UnimplementedSubscriptionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subscription_ServiceDesc, srv)
}

func _Subscription_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).UpdateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_UpdateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).UpdateSubscription(ctx, req.(*UpdateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_UpdateSubscriptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).UpdateSubscriptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_UpdateSubscriptionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).UpdateSubscriptionStatus(ctx, req.(*UpdateSubscriptionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).GetSubscription(ctx, req.(*GetSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_ListSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).ListSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_ListSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).ListSubscription(ctx, req.(*ListSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_SelectSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).SelectSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_SelectSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).SelectSubscription(ctx, req.(*SelectSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_UpdateSubscriptionStrategyGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionStrategyGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).UpdateSubscriptionStrategyGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_UpdateSubscriptionStrategyGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).UpdateSubscriptionStrategyGroups(ctx, req.(*UpdateSubscriptionStrategyGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_UpdateSubscriptionDataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionDataSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).UpdateSubscriptionDataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_UpdateSubscriptionDataSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).UpdateSubscriptionDataSources(ctx, req.(*UpdateSubscriptionDataSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_UpdateSubscriptionAlertLevels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionAlertLevelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).UpdateSubscriptionAlertLevels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_UpdateSubscriptionAlertLevels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).UpdateSubscriptionAlertLevels(ctx, req.(*UpdateSubscriptionAlertLevelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_UpdateSubscriptionNotifyTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionNotifyTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).UpdateSubscriptionNotifyTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_UpdateSubscriptionNotifyTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).UpdateSubscriptionNotifyTypes(ctx, req.(*UpdateSubscriptionNotifyTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Subscription_ServiceDesc is the grpc.ServiceDesc for Subscription service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subscription_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereign.api.v1.Subscription",
	HandlerType: (*SubscriptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubscription",
			Handler:    _Subscription_CreateSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _Subscription_UpdateSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscriptionStatus",
			Handler:    _Subscription_UpdateSubscriptionStatus_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _Subscription_DeleteSubscription_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _Subscription_GetSubscription_Handler,
		},
		{
			MethodName: "ListSubscription",
			Handler:    _Subscription_ListSubscription_Handler,
		},
		{
			MethodName: "SelectSubscription",
			Handler:    _Subscription_SelectSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscriptionStrategyGroups",
			Handler:    _Subscription_UpdateSubscriptionStrategyGroups_Handler,
		},
		{
			MethodName: "UpdateSubscriptionDataSources",
			Handler:    _Subscription_UpdateSubscriptionDataSources_Handler,
		},
		{
			MethodName: "UpdateSubscriptionAlertLevels",
			Handler:    _Subscription_UpdateSubscriptionAlertLevels_Handler,
		},
		{
			MethodName: "UpdateSubscriptionNotifyTypes",
			Handler:    _Subscription_UpdateSubscriptionNotifyTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/subscription.proto",
}
